[Thu Aug 09 11:45:59.189254 2018] [wsgi:info] [pid 3592:tid 139996194957184] mod_wsgi (pid=3592): Attach interpreter ''.
[Thu Aug 09 11:45:59.189501 2018] [wsgi:info] [pid 3592:tid 139996194957184] mod_wsgi (pid=3592): Adding '/home/zahlen/takemeds' to path.
[Thu Aug 09 11:46:05.008152 2018] [wsgi:info] [pid 3592:tid 139996078712576] mod_wsgi (pid=3592): Create interpreter 'www.takemeds.com|'.
[Thu Aug 09 11:46:05.010368 2018] [wsgi:info] [pid 3592:tid 139996078712576] mod_wsgi (pid=3592): Adding '/home/zahlen/takemeds' to path.
[Thu Aug 09 11:46:05.011087 2018] [wsgi:info] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399] mod_wsgi (pid=3592, process='takemeds.com', application='www.takemeds.com|'): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Thu Aug 09 11:46:05.351205 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399] mod_wsgi (pid=3592): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Thu Aug 09 11:46:05.351237 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399] mod_wsgi (pid=3592): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Thu Aug 09 11:46:05.351281 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399] Traceback (most recent call last):
[Thu Aug 09 11:46:05.351316 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 16, in <module>
[Thu Aug 09 11:46:05.351420 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399]     application = get_wsgi_application()
[Thu Aug 09 11:46:05.351476 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399]   File "/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Thu Aug 09 11:46:05.388673 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399]     django.setup(set_prefix=False)
[Thu Aug 09 11:46:05.388731 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399]   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 22, in setup
[Thu Aug 09 11:46:05.396378 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Thu Aug 09 11:46:05.396541 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
[Thu Aug 09 11:46:05.396869 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399]     self._setup(name)
[Thu Aug 09 11:46:05.396917 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
[Thu Aug 09 11:46:05.397035 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399]     self._wrapped = Settings(settings_module)
[Thu Aug 09 11:46:05.397076 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
[Thu Aug 09 11:46:05.397137 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Thu Aug 09 11:46:05.397174 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Thu Aug 09 11:46:05.397346 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399]     __import__(name)
[Thu Aug 09 11:46:05.397386 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 23, in <module>
[Thu Aug 09 11:46:05.397753 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399]     SECRET_KEY = os.environ['SECRET_KEY']
[Thu Aug 09 11:46:05.397806 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399]   File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
[Thu Aug 09 11:46:05.415581 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399]     raise KeyError(key)
[Thu Aug 09 11:46:05.415723 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23399] KeyError: 'SECRET_KEY'
[Thu Aug 09 12:16:50.548770 2018] [wsgi:info] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143] mod_wsgi (pid=3592, process='takemeds.com', application='www.takemeds.com|'): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Thu Aug 09 12:16:50.550948 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143] mod_wsgi (pid=3592): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Thu Aug 09 12:16:50.550989 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143] mod_wsgi (pid=3592): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Thu Aug 09 12:16:50.551040 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143] Traceback (most recent call last):
[Thu Aug 09 12:16:50.551293 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 20, in <module>
[Thu Aug 09 12:16:50.551557 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143]     application = get_wsgi_application()
[Thu Aug 09 12:16:50.551656 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143]   File "/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Thu Aug 09 12:16:50.551721 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143]     django.setup(set_prefix=False)
[Thu Aug 09 12:16:50.551747 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143]   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 22, in setup
[Thu Aug 09 12:16:50.551789 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Thu Aug 09 12:16:50.551813 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
[Thu Aug 09 12:16:50.551851 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143]     self._setup(name)
[Thu Aug 09 12:16:50.551874 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
[Thu Aug 09 12:16:50.551910 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143]     self._wrapped = Settings(settings_module)
[Thu Aug 09 12:16:50.551933 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
[Thu Aug 09 12:16:50.551970 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Thu Aug 09 12:16:50.551992 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Thu Aug 09 12:16:50.552030 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143]     __import__(name)
[Thu Aug 09 12:16:50.552052 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 23, in <module>
[Thu Aug 09 12:16:50.552125 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143]     SECRET_KEY = os.environ['SECRET_KEY']
[Thu Aug 09 12:16:50.552152 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143]   File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
[Thu Aug 09 12:16:50.552221 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143]     raise KeyError(key)
[Thu Aug 09 12:16:50.552271 2018] [wsgi:error] [pid 3592:tid 139996045141760] [remote 192.168.56.1:23143] KeyError: 'SECRET_KEY'
[Thu Aug 09 12:19:52.294837 2018] [wsgi:info] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143] mod_wsgi (pid=3592, process='takemeds.com', application='www.takemeds.com|'): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Thu Aug 09 12:19:52.297461 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143] mod_wsgi (pid=3592): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Thu Aug 09 12:19:52.297521 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143] mod_wsgi (pid=3592): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Thu Aug 09 12:19:52.297570 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143] Traceback (most recent call last):
[Thu Aug 09 12:19:52.297609 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 20, in <module>
[Thu Aug 09 12:19:52.297666 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143]     application = get_wsgi_application()
[Thu Aug 09 12:19:52.297688 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143]   File "/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Thu Aug 09 12:19:52.297766 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143]     django.setup(set_prefix=False)
[Thu Aug 09 12:19:52.297798 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143]   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 22, in setup
[Thu Aug 09 12:19:52.297846 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Thu Aug 09 12:19:52.297878 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
[Thu Aug 09 12:19:52.297935 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143]     self._setup(name)
[Thu Aug 09 12:19:52.297972 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
[Thu Aug 09 12:19:52.298025 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143]     self._wrapped = Settings(settings_module)
[Thu Aug 09 12:19:52.298048 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
[Thu Aug 09 12:19:52.298097 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Thu Aug 09 12:19:52.298128 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Thu Aug 09 12:19:52.298179 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143]     __import__(name)
[Thu Aug 09 12:19:52.298266 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 23, in <module>
[Thu Aug 09 12:19:52.298332 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143]     SECRET_KEY = os.environ['SECRET_KEY']
[Thu Aug 09 12:19:52.298368 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143]   File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
[Thu Aug 09 12:19:52.298418 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143]     raise KeyError(key)
[Thu Aug 09 12:19:52.298584 2018] [wsgi:error] [pid 3592:tid 139996078712576] [remote 192.168.56.1:23143] KeyError: 'SECRET_KEY'
[Thu Aug 09 12:24:23.502471 2018] [wsgi:info] [pid 3592:tid 139996194957184] mod_wsgi (pid=3592): Shutdown requested 'takemeds.com'.
[Thu Aug 09 12:24:23.502790 2018] [wsgi:info] [pid 3592:tid 139996194957184] mod_wsgi (pid=3592): Stopping process 'takemeds.com'.
[Thu Aug 09 12:24:23.502826 2018] [wsgi:info] [pid 3592:tid 139996194957184] mod_wsgi (pid=3592): Destroying interpreters.
[Thu Aug 09 12:24:23.502983 2018] [wsgi:info] [pid 3592:tid 139996194957184] mod_wsgi (pid=3592): Destroy interpreter 'www.takemeds.com|'.
[Thu Aug 09 12:24:23.506874 2018] [wsgi:info] [pid 3592:tid 139996194957184] mod_wsgi (pid=3592): End interpreter 'www.takemeds.com|'.
[Thu Aug 09 12:24:23.527842 2018] [wsgi:info] [pid 3592:tid 139996194957184] mod_wsgi (pid=3592): Cleanup interpreter ''.
[Thu Aug 09 12:24:23.533125 2018] [wsgi:info] [pid 3592:tid 139996194957184] mod_wsgi (pid=3592): Terminating Python.
[Thu Aug 09 12:24:23.570432 2018] [wsgi:info] [pid 3592:tid 139996194957184] mod_wsgi (pid=3592): Python has shutdown.
[Thu Aug 09 12:24:23.570509 2018] [wsgi:info] [pid 3592:tid 139996194957184] mod_wsgi (pid=3592): Exiting process 'takemeds.com'.
[Thu Aug 09 12:50:41.805888 2018] [wsgi:info] [pid 2923:tid 140059424597888] mod_wsgi (pid=2923): Attach interpreter ''.
[Thu Aug 09 12:50:41.819164 2018] [wsgi:info] [pid 2923:tid 140059424597888] mod_wsgi (pid=2923): Adding '/home/zahlen/takemeds' to path.
[Thu Aug 09 13:58:17.127196 2018] [wsgi:info] [pid 2923:tid 140059424597888] mod_wsgi (pid=2923): Shutdown requested 'takemeds.com'.
[Thu Aug 09 13:58:17.127570 2018] [wsgi:info] [pid 2923:tid 140059424597888] mod_wsgi (pid=2923): Stopping process 'takemeds.com'.
[Thu Aug 09 13:58:17.127606 2018] [wsgi:info] [pid 2923:tid 140059424597888] mod_wsgi (pid=2923): Destroying interpreters.
[Thu Aug 09 13:58:17.127661 2018] [wsgi:info] [pid 2923:tid 140059424597888] mod_wsgi (pid=2923): Cleanup interpreter ''.
[Thu Aug 09 13:58:17.144475 2018] [wsgi:info] [pid 2923:tid 140059424597888] mod_wsgi (pid=2923): Terminating Python.
[Thu Aug 09 13:58:17.153366 2018] [wsgi:info] [pid 2923:tid 140059424597888] mod_wsgi (pid=2923): Python has shutdown.
[Thu Aug 09 13:58:17.153407 2018] [wsgi:info] [pid 2923:tid 140059424597888] mod_wsgi (pid=2923): Exiting process 'takemeds.com'.
[Thu Aug 09 13:58:18.302993 2018] [wsgi:info] [pid 3228:tid 139818598856576] mod_wsgi (pid=3228): Attach interpreter ''.
[Thu Aug 09 13:58:18.306926 2018] [wsgi:info] [pid 3228:tid 139818598856576] mod_wsgi (pid=3228): Adding '/home/zahlen/takemeds' to path.
[Thu Aug 09 13:58:42.495596 2018] [wsgi:info] [pid 3228:tid 139818598856576] mod_wsgi (pid=3228): Shutdown requested 'takemeds.com'.
[Thu Aug 09 13:58:42.495982 2018] [wsgi:info] [pid 3228:tid 139818598856576] mod_wsgi (pid=3228): Stopping process 'takemeds.com'.
[Thu Aug 09 13:58:42.496023 2018] [wsgi:info] [pid 3228:tid 139818598856576] mod_wsgi (pid=3228): Destroying interpreters.
[Thu Aug 09 13:58:42.496047 2018] [wsgi:info] [pid 3228:tid 139818598856576] mod_wsgi (pid=3228): Cleanup interpreter ''.
[Thu Aug 09 13:58:42.519073 2018] [wsgi:info] [pid 3228:tid 139818598856576] mod_wsgi (pid=3228): Terminating Python.
[Thu Aug 09 13:58:42.532608 2018] [wsgi:info] [pid 3228:tid 139818598856576] mod_wsgi (pid=3228): Python has shutdown.
[Thu Aug 09 13:58:42.532648 2018] [wsgi:info] [pid 3228:tid 139818598856576] mod_wsgi (pid=3228): Exiting process 'takemeds.com'.
[Thu Aug 09 23:32:48.349489 2018] [wsgi:info] [pid 12878:tid 139727130158976] mod_wsgi (pid=12878): Attach interpreter ''.
[Thu Aug 09 23:32:48.381062 2018] [wsgi:info] [pid 12878:tid 139727130158976] mod_wsgi (pid=12878): Adding '/home/zahlen/takemeds' to path.
[Thu Aug 09 23:32:54.644419 2018] [wsgi:info] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411] mod_wsgi (pid=12878, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Thu Aug 09 23:32:57.519578 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411] mod_wsgi (pid=12878): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Thu Aug 09 23:32:57.519703 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411] mod_wsgi (pid=12878): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Thu Aug 09 23:32:57.550213 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411] Traceback (most recent call last):
[Thu Aug 09 23:32:57.550371 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 20, in <module>
[Thu Aug 09 23:32:57.550390 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]     application = get_wsgi_application()
[Thu Aug 09 23:32:57.550411 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Thu Aug 09 23:32:57.550422 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]     django.setup(set_prefix=False)
[Thu Aug 09 23:32:57.550440 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
[Thu Aug 09 23:32:57.550525 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Thu Aug 09 23:32:57.550582 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Thu Aug 09 23:32:57.550596 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]     self._setup(name)
[Thu Aug 09 23:32:57.550614 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
[Thu Aug 09 23:32:57.550625 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]     self._wrapped = Settings(settings_module)
[Thu Aug 09 23:32:57.550642 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
[Thu Aug 09 23:32:57.550653 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Thu Aug 09 23:32:57.550670 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Thu Aug 09 23:32:57.550681 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]     return _bootstrap._gcd_import(name[level:], package, level)
[Thu Aug 09 23:32:57.550698 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Thu Aug 09 23:32:57.550716 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Thu Aug 09 23:32:57.550735 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Thu Aug 09 23:32:57.550753 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Thu Aug 09 23:32:57.550771 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Thu Aug 09 23:32:57.550790 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Thu Aug 09 23:32:57.550821 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 23, in <module>
[Thu Aug 09 23:32:57.550832 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]     SECRET_KEY = os.environ['SECRET_KEY']
[Thu Aug 09 23:32:57.550850 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/os.py", line 725, in __getitem__
[Thu Aug 09 23:32:57.550860 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411]     raise KeyError(key) from None
[Thu Aug 09 23:32:57.550914 2018] [wsgi:error] [pid 12878:tid 139726987163392] [remote 192.168.56.1:43411] KeyError: 'SECRET_KEY'
[Thu Aug 09 23:39:23.391460 2018] [wsgi:info] [pid 12878:tid 139727130158976] mod_wsgi (pid=12878): Shutdown requested 'takemeds.com'.
[Thu Aug 09 23:39:23.392008 2018] [wsgi:info] [pid 12878:tid 139727130158976] mod_wsgi (pid=12878): Stopping process 'takemeds.com'.
[Thu Aug 09 23:39:23.392049 2018] [wsgi:info] [pid 12878:tid 139727130158976] mod_wsgi (pid=12878): Destroying interpreters.
[Thu Aug 09 23:39:23.392082 2018] [wsgi:info] [pid 12878:tid 139727130158976] mod_wsgi (pid=12878): Cleanup interpreter ''.
[Thu Aug 09 23:39:23.393741 2018] [wsgi:info] [pid 12878:tid 139727130158976] mod_wsgi (pid=12878): Terminating Python.
[Thu Aug 09 23:39:23.469542 2018] [wsgi:info] [pid 12878:tid 139727130158976] mod_wsgi (pid=12878): Python has shutdown.
[Thu Aug 09 23:39:23.469595 2018] [wsgi:info] [pid 12878:tid 139727130158976] mod_wsgi (pid=12878): Exiting process 'takemeds.com'.
[Thu Aug 09 23:39:24.576945 2018] [wsgi:info] [pid 13161:tid 139642710771584] mod_wsgi (pid=13161): Attach interpreter ''.
[Thu Aug 09 23:39:24.594521 2018] [wsgi:info] [pid 13161:tid 139642710771584] mod_wsgi (pid=13161): Adding '/home/zahlen/takemeds' to path.
[Thu Aug 09 23:39:28.786331 2018] [wsgi:info] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964] mod_wsgi (pid=13161, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Thu Aug 09 23:39:29.272641 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964] mod_wsgi (pid=13161): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Thu Aug 09 23:39:29.272750 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964] mod_wsgi (pid=13161): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Thu Aug 09 23:39:29.274963 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964] Traceback (most recent call last):
[Thu Aug 09 23:39:29.275056 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 20, in <module>
[Thu Aug 09 23:39:29.275070 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]     application = get_wsgi_application()
[Thu Aug 09 23:39:29.275159 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Thu Aug 09 23:39:29.275174 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]     django.setup(set_prefix=False)
[Thu Aug 09 23:39:29.275194 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
[Thu Aug 09 23:39:29.275205 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Thu Aug 09 23:39:29.275223 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Thu Aug 09 23:39:29.275245 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]     self._setup(name)
[Thu Aug 09 23:39:29.275264 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
[Thu Aug 09 23:39:29.275274 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]     self._wrapped = Settings(settings_module)
[Thu Aug 09 23:39:29.275292 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
[Thu Aug 09 23:39:29.275302 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Thu Aug 09 23:39:29.275319 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Thu Aug 09 23:39:29.275329 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]     return _bootstrap._gcd_import(name[level:], package, level)
[Thu Aug 09 23:39:29.275346 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Thu Aug 09 23:39:29.275364 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Thu Aug 09 23:39:29.275383 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Thu Aug 09 23:39:29.275401 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Thu Aug 09 23:39:29.275419 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Thu Aug 09 23:39:29.275437 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Thu Aug 09 23:39:29.275455 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 23, in <module>
[Thu Aug 09 23:39:29.275465 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]     SECRET_KEY = os.environ['SECRET_KEY']
[Thu Aug 09 23:39:29.275483 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/os.py", line 725, in __getitem__
[Thu Aug 09 23:39:29.275493 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964]     raise KeyError(key) from None
[Thu Aug 09 23:39:29.275541 2018] [wsgi:error] [pid 13161:tid 139642584561408] [remote 192.168.56.1:43964] KeyError: 'SECRET_KEY'
[Thu Aug 09 23:43:49.859891 2018] [wsgi:info] [pid 13161:tid 139642710771584] mod_wsgi (pid=13161): Shutdown requested 'takemeds.com'.
[Thu Aug 09 23:43:49.860263 2018] [wsgi:info] [pid 13161:tid 139642710771584] mod_wsgi (pid=13161): Stopping process 'takemeds.com'.
[Thu Aug 09 23:43:49.860304 2018] [wsgi:info] [pid 13161:tid 139642710771584] mod_wsgi (pid=13161): Destroying interpreters.
[Thu Aug 09 23:43:49.860376 2018] [wsgi:info] [pid 13161:tid 139642710771584] mod_wsgi (pid=13161): Cleanup interpreter ''.
[Thu Aug 09 23:43:49.862921 2018] [wsgi:info] [pid 13161:tid 139642710771584] mod_wsgi (pid=13161): Terminating Python.
[Thu Aug 09 23:43:49.934733 2018] [wsgi:info] [pid 13161:tid 139642710771584] mod_wsgi (pid=13161): Python has shutdown.
[Thu Aug 09 23:43:49.934781 2018] [wsgi:info] [pid 13161:tid 139642710771584] mod_wsgi (pid=13161): Exiting process 'takemeds.com'.
[Thu Aug 09 23:43:51.034286 2018] [wsgi:info] [pid 13491:tid 140314146994048] mod_wsgi (pid=13491): Attach interpreter ''.
[Thu Aug 09 23:43:51.056124 2018] [wsgi:info] [pid 13491:tid 140314146994048] mod_wsgi (pid=13491): Adding '/home/zahlen/takemeds' to path.
[Thu Aug 09 23:43:59.746954 2018] [wsgi:info] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355] mod_wsgi (pid=13491, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Thu Aug 09 23:44:00.286311 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355] mod_wsgi (pid=13491): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Thu Aug 09 23:44:00.286458 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355] mod_wsgi (pid=13491): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Thu Aug 09 23:44:00.291068 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355] Traceback (most recent call last):
[Thu Aug 09 23:44:00.291213 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 20, in <module>
[Thu Aug 09 23:44:00.291236 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]     application = get_wsgi_application()
[Thu Aug 09 23:44:00.291266 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Thu Aug 09 23:44:00.291284 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]     django.setup(set_prefix=False)
[Thu Aug 09 23:44:00.291312 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
[Thu Aug 09 23:44:00.291328 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Thu Aug 09 23:44:00.291354 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Thu Aug 09 23:44:00.291371 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]     self._setup(name)
[Thu Aug 09 23:44:00.291398 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
[Thu Aug 09 23:44:00.291505 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]     self._wrapped = Settings(settings_module)
[Thu Aug 09 23:44:00.291545 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
[Thu Aug 09 23:44:00.291561 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Thu Aug 09 23:44:00.291582 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Thu Aug 09 23:44:00.291598 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]     return _bootstrap._gcd_import(name[level:], package, level)
[Thu Aug 09 23:44:00.291623 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Thu Aug 09 23:44:00.291653 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Thu Aug 09 23:44:00.291699 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Thu Aug 09 23:44:00.291729 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Thu Aug 09 23:44:00.291758 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Thu Aug 09 23:44:00.291786 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Thu Aug 09 23:44:00.291814 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 23, in <module>
[Thu Aug 09 23:44:00.291829 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]     SECRET_KEY = os.environ['SECRET_KEY']
[Thu Aug 09 23:44:00.291856 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/os.py", line 725, in __getitem__
[Thu Aug 09 23:44:00.291870 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355]     raise KeyError(key) from None
[Thu Aug 09 23:44:00.291970 2018] [wsgi:error] [pid 13491:tid 140314020783872] [remote 192.168.56.1:44355] KeyError: 'SECRET_KEY'
[Thu Aug 09 23:46:43.030801 2018] [wsgi:info] [pid 13491:tid 140314146994048] mod_wsgi (pid=13491): Shutdown requested 'takemeds.com'.
[Thu Aug 09 23:46:43.030991 2018] [wsgi:info] [pid 13491:tid 140314146994048] mod_wsgi (pid=13491): Stopping process 'takemeds.com'.
[Thu Aug 09 23:46:43.031015 2018] [wsgi:info] [pid 13491:tid 140314146994048] mod_wsgi (pid=13491): Destroying interpreters.
[Thu Aug 09 23:46:43.031029 2018] [wsgi:info] [pid 13491:tid 140314146994048] mod_wsgi (pid=13491): Cleanup interpreter ''.
[Thu Aug 09 23:46:43.031985 2018] [wsgi:info] [pid 13491:tid 140314146994048] mod_wsgi (pid=13491): Terminating Python.
[Thu Aug 09 23:46:43.105093 2018] [wsgi:info] [pid 13491:tid 140314146994048] mod_wsgi (pid=13491): Python has shutdown.
[Thu Aug 09 23:46:43.105141 2018] [wsgi:info] [pid 13491:tid 140314146994048] mod_wsgi (pid=13491): Exiting process 'takemeds.com'.
[Thu Aug 09 23:46:44.249404 2018] [wsgi:info] [pid 13657:tid 140209372231552] mod_wsgi (pid=13657): Attach interpreter ''.
[Thu Aug 09 23:46:44.275022 2018] [wsgi:info] [pid 13657:tid 140209372231552] mod_wsgi (pid=13657): Adding '/home/zahlen/takemeds' to path.
[Thu Aug 09 23:46:48.555866 2018] [wsgi:info] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582] mod_wsgi (pid=13657, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Thu Aug 09 23:46:49.052226 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582] mod_wsgi (pid=13657): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Thu Aug 09 23:46:49.052428 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582] mod_wsgi (pid=13657): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Thu Aug 09 23:46:49.058558 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582] Traceback (most recent call last):
[Thu Aug 09 23:46:49.058722 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 20, in <module>
[Thu Aug 09 23:46:49.058745 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]     application = get_wsgi_application()
[Thu Aug 09 23:46:49.058779 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Thu Aug 09 23:46:49.058798 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]     django.setup(set_prefix=False)
[Thu Aug 09 23:46:49.058845 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
[Thu Aug 09 23:46:49.058932 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Thu Aug 09 23:46:49.058974 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Thu Aug 09 23:46:49.058992 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]     self._setup(name)
[Thu Aug 09 23:46:49.059017 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
[Thu Aug 09 23:46:49.059033 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]     self._wrapped = Settings(settings_module)
[Thu Aug 09 23:46:49.059062 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
[Thu Aug 09 23:46:49.059079 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Thu Aug 09 23:46:49.059105 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Thu Aug 09 23:46:49.059120 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]     return _bootstrap._gcd_import(name[level:], package, level)
[Thu Aug 09 23:46:49.059148 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Thu Aug 09 23:46:49.059179 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Thu Aug 09 23:46:49.059207 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Thu Aug 09 23:46:49.059235 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Thu Aug 09 23:46:49.059266 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Thu Aug 09 23:46:49.059294 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Thu Aug 09 23:46:49.059323 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 23, in <module>
[Thu Aug 09 23:46:49.059339 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]     print (os.environ['SECRET_KEY'])
[Thu Aug 09 23:46:49.059457 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/os.py", line 725, in __getitem__
[Thu Aug 09 23:46:49.059478 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582]     raise KeyError(key) from None
[Thu Aug 09 23:46:49.059538 2018] [wsgi:error] [pid 13657:tid 140209246021376] [remote 192.168.56.1:44582] KeyError: 'SECRET_KEY'
[Thu Aug 09 23:47:22.482683 2018] [wsgi:info] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629] mod_wsgi (pid=13657, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Thu Aug 09 23:47:22.496552 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629] mod_wsgi (pid=13657): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Thu Aug 09 23:47:22.496679 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629] mod_wsgi (pid=13657): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Thu Aug 09 23:47:22.498077 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629] Traceback (most recent call last):
[Thu Aug 09 23:47:22.498209 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 20, in <module>
[Thu Aug 09 23:47:22.498228 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]     application = get_wsgi_application()
[Thu Aug 09 23:47:22.498254 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Thu Aug 09 23:47:22.498269 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]     django.setup(set_prefix=False)
[Thu Aug 09 23:47:22.498293 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
[Thu Aug 09 23:47:22.498307 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Thu Aug 09 23:47:22.498330 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Thu Aug 09 23:47:22.498344 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]     self._setup(name)
[Thu Aug 09 23:47:22.498367 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
[Thu Aug 09 23:47:22.498380 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]     self._wrapped = Settings(settings_module)
[Thu Aug 09 23:47:22.498403 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
[Thu Aug 09 23:47:22.498439 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Thu Aug 09 23:47:22.498467 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Thu Aug 09 23:47:22.498481 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]     return _bootstrap._gcd_import(name[level:], package, level)
[Thu Aug 09 23:47:22.498504 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Thu Aug 09 23:47:22.498528 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Thu Aug 09 23:47:22.498552 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Thu Aug 09 23:47:22.498576 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Thu Aug 09 23:47:22.498600 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Thu Aug 09 23:47:22.498624 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Thu Aug 09 23:47:22.498670 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 83, in <module>
[Thu Aug 09 23:47:22.498685 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]     'NAME': os.environ['DB_NAME'],
[Thu Aug 09 23:47:22.498708 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/os.py", line 725, in __getitem__
[Thu Aug 09 23:47:22.498722 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629]     raise KeyError(key) from None
[Thu Aug 09 23:47:22.498767 2018] [wsgi:error] [pid 13657:tid 140209254414080] [remote 192.168.56.1:44629] KeyError: 'DB_NAME'
[Thu Aug 09 23:47:26.031537 2018] [wsgi:info] [pid 13657:tid 140209372231552] mod_wsgi (pid=13657): Shutdown requested 'takemeds.com'.
[Thu Aug 09 23:47:26.031944 2018] [wsgi:info] [pid 13657:tid 140209372231552] mod_wsgi (pid=13657): Stopping process 'takemeds.com'.
[Thu Aug 09 23:47:26.031986 2018] [wsgi:info] [pid 13657:tid 140209372231552] mod_wsgi (pid=13657): Destroying interpreters.
[Thu Aug 09 23:47:26.032010 2018] [wsgi:info] [pid 13657:tid 140209372231552] mod_wsgi (pid=13657): Cleanup interpreter ''.
[Thu Aug 09 23:47:26.034211 2018] [wsgi:info] [pid 13657:tid 140209372231552] mod_wsgi (pid=13657): Terminating Python.
[Thu Aug 09 23:47:26.112299 2018] [wsgi:info] [pid 13657:tid 140209372231552] mod_wsgi (pid=13657): Python has shutdown.
[Thu Aug 09 23:47:26.112375 2018] [wsgi:info] [pid 13657:tid 140209372231552] mod_wsgi (pid=13657): Exiting process 'takemeds.com'.
[Thu Aug 09 23:47:27.242988 2018] [wsgi:info] [pid 13775:tid 140195594127232] mod_wsgi (pid=13775): Attach interpreter ''.
[Thu Aug 09 23:47:27.262487 2018] [wsgi:info] [pid 13775:tid 140195594127232] mod_wsgi (pid=13775): Adding '/home/zahlen/takemeds' to path.
[Thu Aug 09 23:47:33.491040 2018] [wsgi:info] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649] mod_wsgi (pid=13775, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Thu Aug 09 23:47:33.960304 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649] mod_wsgi (pid=13775): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Thu Aug 09 23:47:33.960400 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649] mod_wsgi (pid=13775): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Thu Aug 09 23:47:33.962763 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649] Traceback (most recent call last):
[Thu Aug 09 23:47:33.962860 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 20, in <module>
[Thu Aug 09 23:47:33.962874 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]     application = get_wsgi_application()
[Thu Aug 09 23:47:33.962895 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Thu Aug 09 23:47:33.962905 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]     django.setup(set_prefix=False)
[Thu Aug 09 23:47:33.962924 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
[Thu Aug 09 23:47:33.962935 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Thu Aug 09 23:47:33.963010 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Thu Aug 09 23:47:33.963038 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]     self._setup(name)
[Thu Aug 09 23:47:33.963062 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
[Thu Aug 09 23:47:33.963073 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]     self._wrapped = Settings(settings_module)
[Thu Aug 09 23:47:33.963091 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
[Thu Aug 09 23:47:33.963102 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Thu Aug 09 23:47:33.963119 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Thu Aug 09 23:47:33.963130 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]     return _bootstrap._gcd_import(name[level:], package, level)
[Thu Aug 09 23:47:33.963148 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Thu Aug 09 23:47:33.963166 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Thu Aug 09 23:47:33.963185 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Thu Aug 09 23:47:33.963204 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Thu Aug 09 23:47:33.963223 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Thu Aug 09 23:47:33.963241 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Thu Aug 09 23:47:33.963260 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 83, in <module>
[Thu Aug 09 23:47:33.963271 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]     'NAME': os.environ['DB_NAME'],
[Thu Aug 09 23:47:33.963288 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/os.py", line 725, in __getitem__
[Thu Aug 09 23:47:33.963299 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649]     raise KeyError(key) from None
[Thu Aug 09 23:47:33.963349 2018] [wsgi:error] [pid 13775:tid 140195467917056] [remote 192.168.56.1:44649] KeyError: 'DB_NAME'
[Fri Aug 10 00:08:22.644488 2018] [wsgi:info] [pid 13775:tid 140195594127232] mod_wsgi (pid=13775): Shutdown requested 'takemeds.com'.
[Fri Aug 10 00:08:22.644709 2018] [wsgi:info] [pid 13775:tid 140195594127232] mod_wsgi (pid=13775): Stopping process 'takemeds.com'.
[Fri Aug 10 00:08:22.644731 2018] [wsgi:info] [pid 13775:tid 140195594127232] mod_wsgi (pid=13775): Destroying interpreters.
[Fri Aug 10 00:08:22.644749 2018] [wsgi:info] [pid 13775:tid 140195594127232] mod_wsgi (pid=13775): Cleanup interpreter ''.
[Fri Aug 10 00:08:22.645944 2018] [wsgi:info] [pid 13775:tid 140195594127232] mod_wsgi (pid=13775): Terminating Python.
[Fri Aug 10 00:08:22.709570 2018] [wsgi:info] [pid 13775:tid 140195594127232] mod_wsgi (pid=13775): Python has shutdown.
[Fri Aug 10 00:08:22.709616 2018] [wsgi:info] [pid 13775:tid 140195594127232] mod_wsgi (pid=13775): Exiting process 'takemeds.com'.
[Fri Aug 10 00:08:23.820032 2018] [wsgi:info] [pid 13938:tid 140313522034560] mod_wsgi (pid=13938): Attach interpreter ''.
[Fri Aug 10 00:08:23.841294 2018] [wsgi:info] [pid 13938:tid 140313522034560] mod_wsgi (pid=13938): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 00:08:31.092498 2018] [wsgi:info] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506] mod_wsgi (pid=13938, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 00:08:31.560819 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506] mod_wsgi (pid=13938): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Fri Aug 10 00:08:31.561028 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506] mod_wsgi (pid=13938): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 00:08:31.564019 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506] Traceback (most recent call last):
[Fri Aug 10 00:08:31.564139 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 20, in <module>
[Fri Aug 10 00:08:31.564159 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]     application = get_wsgi_application()
[Fri Aug 10 00:08:31.564181 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Fri Aug 10 00:08:31.564195 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]     django.setup(set_prefix=False)
[Fri Aug 10 00:08:31.564214 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
[Fri Aug 10 00:08:31.564226 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Fri Aug 10 00:08:31.564244 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Fri Aug 10 00:08:31.564255 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]     self._setup(name)
[Fri Aug 10 00:08:31.564272 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
[Fri Aug 10 00:08:31.564283 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]     self._wrapped = Settings(settings_module)
[Fri Aug 10 00:08:31.564301 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
[Fri Aug 10 00:08:31.564312 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Fri Aug 10 00:08:31.564329 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Fri Aug 10 00:08:31.564339 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Aug 10 00:08:31.564380 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Fri Aug 10 00:08:31.564399 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Fri Aug 10 00:08:31.564432 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Fri Aug 10 00:08:31.564451 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Fri Aug 10 00:08:31.564470 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Fri Aug 10 00:08:31.564488 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Fri Aug 10 00:08:31.564506 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 83, in <module>
[Fri Aug 10 00:08:31.564517 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]     'NAME': os.environ['DB_NAME'],
[Fri Aug 10 00:08:31.564534 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/os.py", line 725, in __getitem__
[Fri Aug 10 00:08:31.564545 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506]     raise KeyError(key) from None
[Fri Aug 10 00:08:31.564595 2018] [wsgi:error] [pid 13938:tid 140313395824384] [remote 192.168.56.1:46506] KeyError: 'DB_NAME'
[Fri Aug 10 00:10:00.978792 2018] [wsgi:info] [pid 13938:tid 140313522034560] mod_wsgi (pid=13938): Shutdown requested 'takemeds.com'.
[Fri Aug 10 00:10:00.979252 2018] [wsgi:info] [pid 13938:tid 140313522034560] mod_wsgi (pid=13938): Stopping process 'takemeds.com'.
[Fri Aug 10 00:10:00.979304 2018] [wsgi:info] [pid 13938:tid 140313522034560] mod_wsgi (pid=13938): Destroying interpreters.
[Fri Aug 10 00:10:00.979384 2018] [wsgi:info] [pid 13938:tid 140313522034560] mod_wsgi (pid=13938): Cleanup interpreter ''.
[Fri Aug 10 00:10:00.980111 2018] [wsgi:info] [pid 13938:tid 140313522034560] mod_wsgi (pid=13938): Terminating Python.
[Fri Aug 10 00:10:01.055396 2018] [wsgi:info] [pid 13938:tid 140313522034560] mod_wsgi (pid=13938): Python has shutdown.
[Fri Aug 10 00:10:01.055454 2018] [wsgi:info] [pid 13938:tid 140313522034560] mod_wsgi (pid=13938): Exiting process 'takemeds.com'.
[Fri Aug 10 00:10:02.169107 2018] [wsgi:info] [pid 14096:tid 139766551021440] mod_wsgi (pid=14096): Attach interpreter ''.
[Fri Aug 10 00:10:02.189450 2018] [wsgi:info] [pid 14096:tid 139766551021440] mod_wsgi (pid=14096): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 00:10:10.937359 2018] [wsgi:info] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642] mod_wsgi (pid=14096, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 00:10:11.422220 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642] mod_wsgi (pid=14096): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Fri Aug 10 00:10:11.422388 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642] mod_wsgi (pid=14096): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 00:10:11.428365 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642] Traceback (most recent call last):
[Fri Aug 10 00:10:11.428654 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 20, in <module>
[Fri Aug 10 00:10:11.428689 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]     application = get_wsgi_application()
[Fri Aug 10 00:10:11.428715 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Fri Aug 10 00:10:11.428727 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]     django.setup(set_prefix=False)
[Fri Aug 10 00:10:11.428762 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
[Fri Aug 10 00:10:11.428774 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Fri Aug 10 00:10:11.428793 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Fri Aug 10 00:10:11.428804 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]     self._setup(name)
[Fri Aug 10 00:10:11.428821 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
[Fri Aug 10 00:10:11.428832 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]     self._wrapped = Settings(settings_module)
[Fri Aug 10 00:10:11.428849 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
[Fri Aug 10 00:10:11.428860 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Fri Aug 10 00:10:11.428877 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Fri Aug 10 00:10:11.428888 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Aug 10 00:10:11.428906 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Fri Aug 10 00:10:11.428924 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Fri Aug 10 00:10:11.428943 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Fri Aug 10 00:10:11.428961 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Fri Aug 10 00:10:11.428980 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Fri Aug 10 00:10:11.428998 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Fri Aug 10 00:10:11.429017 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 83, in <module>
[Fri Aug 10 00:10:11.429090 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]     'NAME': os.environ['DB_NAME'],
[Fri Aug 10 00:10:11.429137 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/os.py", line 725, in __getitem__
[Fri Aug 10 00:10:11.429157 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642]     raise KeyError(key) from None
[Fri Aug 10 00:10:11.429239 2018] [wsgi:error] [pid 14096:tid 139766424811264] [remote 192.168.56.1:46642] KeyError: 'DB_NAME'
[Fri Aug 10 00:22:19.090762 2018] [wsgi:info] [pid 14096:tid 139766551021440] mod_wsgi (pid=14096): Shutdown requested 'takemeds.com'.
[Fri Aug 10 00:22:19.091140 2018] [wsgi:info] [pid 14096:tid 139766551021440] mod_wsgi (pid=14096): Stopping process 'takemeds.com'.
[Fri Aug 10 00:22:19.091320 2018] [wsgi:info] [pid 14096:tid 139766551021440] mod_wsgi (pid=14096): Destroying interpreters.
[Fri Aug 10 00:22:19.091358 2018] [wsgi:info] [pid 14096:tid 139766551021440] mod_wsgi (pid=14096): Cleanup interpreter ''.
[Fri Aug 10 00:22:19.093814 2018] [wsgi:info] [pid 14096:tid 139766551021440] mod_wsgi (pid=14096): Terminating Python.
[Fri Aug 10 00:22:19.164959 2018] [wsgi:info] [pid 14096:tid 139766551021440] mod_wsgi (pid=14096): Python has shutdown.
[Fri Aug 10 00:22:19.165006 2018] [wsgi:info] [pid 14096:tid 139766551021440] mod_wsgi (pid=14096): Exiting process 'takemeds.com'.
[Fri Aug 10 00:22:20.283548 2018] [wsgi:info] [pid 14349:tid 140171594020736] mod_wsgi (pid=14349): Attach interpreter ''.
[Fri Aug 10 00:22:20.299500 2018] [wsgi:info] [pid 14349:tid 140171594020736] mod_wsgi (pid=14349): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 00:22:26.876052 2018] [wsgi:info] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673] mod_wsgi (pid=14349, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 00:22:27.353391 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673] mod_wsgi (pid=14349): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Fri Aug 10 00:22:27.353637 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673] mod_wsgi (pid=14349): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 00:22:27.355906 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673] Traceback (most recent call last):
[Fri Aug 10 00:22:27.356035 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 20, in <module>
[Fri Aug 10 00:22:27.356052 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]     application = get_wsgi_application()
[Fri Aug 10 00:22:27.356073 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Fri Aug 10 00:22:27.356085 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]     django.setup(set_prefix=False)
[Fri Aug 10 00:22:27.356103 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
[Fri Aug 10 00:22:27.356114 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Fri Aug 10 00:22:27.356132 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Fri Aug 10 00:22:27.356142 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]     self._setup(name)
[Fri Aug 10 00:22:27.356160 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
[Fri Aug 10 00:22:27.356170 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]     self._wrapped = Settings(settings_module)
[Fri Aug 10 00:22:27.356188 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
[Fri Aug 10 00:22:27.356198 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Fri Aug 10 00:22:27.356215 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Fri Aug 10 00:22:27.356238 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Aug 10 00:22:27.356258 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Fri Aug 10 00:22:27.356277 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Fri Aug 10 00:22:27.356296 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Fri Aug 10 00:22:27.356314 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Fri Aug 10 00:22:27.356332 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Fri Aug 10 00:22:27.356350 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Fri Aug 10 00:22:27.356368 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 83, in <module>
[Fri Aug 10 00:22:27.356379 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]     'NAME': os.environ['DB_NAME'],
[Fri Aug 10 00:22:27.356396 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/os.py", line 725, in __getitem__
[Fri Aug 10 00:22:27.356406 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673]     raise KeyError(key) from None
[Fri Aug 10 00:22:27.356477 2018] [wsgi:error] [pid 14349:tid 140171467810560] [remote 192.168.56.1:47673] KeyError: 'DB_NAME'
[Fri Aug 10 00:31:58.365722 2018] [wsgi:info] [pid 14349:tid 140171594020736] mod_wsgi (pid=14349): Shutdown requested 'takemeds.com'.
[Fri Aug 10 00:31:58.366086 2018] [wsgi:info] [pid 14349:tid 140171594020736] mod_wsgi (pid=14349): Stopping process 'takemeds.com'.
[Fri Aug 10 00:31:58.366174 2018] [wsgi:info] [pid 14349:tid 140171594020736] mod_wsgi (pid=14349): Destroying interpreters.
[Fri Aug 10 00:31:58.366214 2018] [wsgi:info] [pid 14349:tid 140171594020736] mod_wsgi (pid=14349): Cleanup interpreter ''.
[Fri Aug 10 00:31:58.368206 2018] [wsgi:info] [pid 14349:tid 140171594020736] mod_wsgi (pid=14349): Terminating Python.
[Fri Aug 10 00:31:58.446642 2018] [wsgi:info] [pid 14349:tid 140171594020736] mod_wsgi (pid=14349): Python has shutdown.
[Fri Aug 10 00:31:58.446690 2018] [wsgi:info] [pid 14349:tid 140171594020736] mod_wsgi (pid=14349): Exiting process 'takemeds.com'.
[Fri Aug 10 00:31:59.566923 2018] [wsgi:info] [pid 14500:tid 140693931063168] mod_wsgi (pid=14500): Attach interpreter ''.
[Fri Aug 10 00:31:59.592145 2018] [wsgi:info] [pid 14500:tid 140693931063168] mod_wsgi (pid=14500): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 02:41:18.910566 2018] [wsgi:info] [pid 14500:tid 140693931063168] mod_wsgi (pid=14500): Shutdown requested 'takemeds.com'.
[Fri Aug 10 02:41:18.911085 2018] [wsgi:info] [pid 14500:tid 140693931063168] mod_wsgi (pid=14500): Stopping process 'takemeds.com'.
[Fri Aug 10 02:41:18.911182 2018] [wsgi:info] [pid 14500:tid 140693931063168] mod_wsgi (pid=14500): Destroying interpreters.
[Fri Aug 10 02:41:18.911211 2018] [wsgi:info] [pid 14500:tid 140693931063168] mod_wsgi (pid=14500): Cleanup interpreter ''.
[Fri Aug 10 02:41:18.936402 2018] [wsgi:info] [pid 14500:tid 140693931063168] mod_wsgi (pid=14500): Terminating Python.
[Fri Aug 10 02:41:18.954322 2018] [wsgi:info] [pid 14500:tid 140693931063168] mod_wsgi (pid=14500): Python has shutdown.
[Fri Aug 10 02:41:18.954389 2018] [wsgi:info] [pid 14500:tid 140693931063168] mod_wsgi (pid=14500): Exiting process 'takemeds.com'.
[Fri Aug 10 02:41:20.140792 2018] [wsgi:info] [pid 15228:tid 139695608567680] mod_wsgi (pid=15228): Attach interpreter ''.
[Fri Aug 10 02:41:20.158730 2018] [wsgi:info] [pid 15228:tid 139695608567680] mod_wsgi (pid=15228): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 02:41:30.600092 2018] [wsgi:info] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380] mod_wsgi (pid=15228, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 02:41:31.721121 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380] mod_wsgi (pid=15228): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Fri Aug 10 02:41:31.721226 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380] mod_wsgi (pid=15228): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 02:41:31.723871 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380] Traceback (most recent call last):
[Fri Aug 10 02:41:31.723975 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 20, in <module>
[Fri Aug 10 02:41:31.723991 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]     application = get_wsgi_application()
[Fri Aug 10 02:41:31.724010 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Fri Aug 10 02:41:31.724021 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]     django.setup(set_prefix=False)
[Fri Aug 10 02:41:31.724040 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
[Fri Aug 10 02:41:31.724050 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Fri Aug 10 02:41:31.724068 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Fri Aug 10 02:41:31.724078 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]     self._setup(name)
[Fri Aug 10 02:41:31.724095 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
[Fri Aug 10 02:41:31.724106 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]     self._wrapped = Settings(settings_module)
[Fri Aug 10 02:41:31.724123 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
[Fri Aug 10 02:41:31.724134 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Fri Aug 10 02:41:31.724151 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Fri Aug 10 02:41:31.724161 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Aug 10 02:41:31.724179 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Fri Aug 10 02:41:31.724197 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Fri Aug 10 02:41:31.724216 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Fri Aug 10 02:41:31.724247 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Fri Aug 10 02:41:31.724267 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Fri Aug 10 02:41:31.724285 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Fri Aug 10 02:41:31.724304 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 83, in <module>
[Fri Aug 10 02:41:31.724314 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]     'NAME': os.environ['DB_NAME'],
[Fri Aug 10 02:41:31.724355 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/os.py", line 725, in __getitem__
[Fri Aug 10 02:41:31.724368 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380]     raise KeyError(key) from None
[Fri Aug 10 02:41:31.724417 2018] [wsgi:error] [pid 15228:tid 139695482357504] [remote 192.168.56.1:59380] KeyError: 'DB_NAME'
[Fri Aug 10 02:55:57.711929 2018] [wsgi:info] [pid 15228:tid 139695608567680] mod_wsgi (pid=15228): Shutdown requested 'takemeds.com'.
[Fri Aug 10 02:55:57.712383 2018] [wsgi:info] [pid 15228:tid 139695608567680] mod_wsgi (pid=15228): Stopping process 'takemeds.com'.
[Fri Aug 10 02:55:57.712432 2018] [wsgi:info] [pid 15228:tid 139695608567680] mod_wsgi (pid=15228): Destroying interpreters.
[Fri Aug 10 02:55:57.712462 2018] [wsgi:info] [pid 15228:tid 139695608567680] mod_wsgi (pid=15228): Cleanup interpreter ''.
[Fri Aug 10 02:55:57.714647 2018] [wsgi:info] [pid 15228:tid 139695608567680] mod_wsgi (pid=15228): Terminating Python.
[Fri Aug 10 02:55:57.789346 2018] [wsgi:info] [pid 15228:tid 139695608567680] mod_wsgi (pid=15228): Python has shutdown.
[Fri Aug 10 02:55:57.789407 2018] [wsgi:info] [pid 15228:tid 139695608567680] mod_wsgi (pid=15228): Exiting process 'takemeds.com'.
[Fri Aug 10 02:55:58.931013 2018] [wsgi:info] [pid 15427:tid 140353186994048] mod_wsgi (pid=15427): Attach interpreter ''.
[Fri Aug 10 02:55:58.948983 2018] [wsgi:info] [pid 15427:tid 140353186994048] mod_wsgi (pid=15427): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 02:56:32.052314 2018] [wsgi:info] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645] mod_wsgi (pid=15427, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 02:56:33.431381 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645] mod_wsgi (pid=15427): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Fri Aug 10 02:56:33.431499 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645] mod_wsgi (pid=15427): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 02:56:33.433782 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645] Traceback (most recent call last):
[Fri Aug 10 02:56:33.433879 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 20, in <module>
[Fri Aug 10 02:56:33.433894 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]     application = get_wsgi_application()
[Fri Aug 10 02:56:33.433915 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Fri Aug 10 02:56:33.433927 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]     django.setup(set_prefix=False)
[Fri Aug 10 02:56:33.433959 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
[Fri Aug 10 02:56:33.433971 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Fri Aug 10 02:56:33.433989 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Fri Aug 10 02:56:33.434000 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]     self._setup(name)
[Fri Aug 10 02:56:33.434018 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
[Fri Aug 10 02:56:33.434028 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]     self._wrapped = Settings(settings_module)
[Fri Aug 10 02:56:33.434046 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
[Fri Aug 10 02:56:33.434056 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Fri Aug 10 02:56:33.434074 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Fri Aug 10 02:56:33.434084 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Aug 10 02:56:33.434102 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Fri Aug 10 02:56:33.434121 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Fri Aug 10 02:56:33.434140 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Fri Aug 10 02:56:33.434158 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Fri Aug 10 02:56:33.434210 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Fri Aug 10 02:56:33.434236 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Fri Aug 10 02:56:33.434260 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 83, in <module>
[Fri Aug 10 02:56:33.434272 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]     'NAME': os.environ['DB_NAME'],
[Fri Aug 10 02:56:33.434294 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/os.py", line 725, in __getitem__
[Fri Aug 10 02:56:33.434306 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645]     raise KeyError(key) from None
[Fri Aug 10 02:56:33.434365 2018] [wsgi:error] [pid 15427:tid 140353060783872] [remote 192.168.56.1:60645] KeyError: 'DB_NAME'
[Fri Aug 10 02:57:19.448281 2018] [wsgi:info] [pid 15427:tid 140353186994048] mod_wsgi (pid=15427): Shutdown requested 'takemeds.com'.
[Fri Aug 10 02:57:19.448546 2018] [wsgi:info] [pid 15427:tid 140353186994048] mod_wsgi (pid=15427): Stopping process 'takemeds.com'.
[Fri Aug 10 02:57:19.448575 2018] [wsgi:info] [pid 15427:tid 140353186994048] mod_wsgi (pid=15427): Destroying interpreters.
[Fri Aug 10 02:57:19.448615 2018] [wsgi:info] [pid 15427:tid 140353186994048] mod_wsgi (pid=15427): Cleanup interpreter ''.
[Fri Aug 10 02:57:19.449539 2018] [wsgi:info] [pid 15427:tid 140353186994048] mod_wsgi (pid=15427): Terminating Python.
[Fri Aug 10 02:57:19.521526 2018] [wsgi:info] [pid 15427:tid 140353186994048] mod_wsgi (pid=15427): Python has shutdown.
[Fri Aug 10 02:57:19.521574 2018] [wsgi:info] [pid 15427:tid 140353186994048] mod_wsgi (pid=15427): Exiting process 'takemeds.com'.
[Fri Aug 10 02:57:28.649229 2018] [wsgi:info] [pid 15548:tid 140434452752256] mod_wsgi (pid=15548): Attach interpreter ''.
[Fri Aug 10 02:57:28.666123 2018] [wsgi:info] [pid 15548:tid 140434452752256] mod_wsgi (pid=15548): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 02:59:48.222217 2018] [wsgi:info] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912] mod_wsgi (pid=15548, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 02:59:49.052872 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912] mod_wsgi (pid=15548): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Fri Aug 10 02:59:49.053004 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912] mod_wsgi (pid=15548): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 02:59:49.076050 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912] Traceback (most recent call last):
[Fri Aug 10 02:59:49.076193 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 20, in <module>
[Fri Aug 10 02:59:49.076210 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]     application = get_wsgi_application()
[Fri Aug 10 02:59:49.076231 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Fri Aug 10 02:59:49.076242 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]     django.setup(set_prefix=False)
[Fri Aug 10 02:59:49.076260 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
[Fri Aug 10 02:59:49.076271 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Fri Aug 10 02:59:49.076290 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Fri Aug 10 02:59:49.076300 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]     self._setup(name)
[Fri Aug 10 02:59:49.076318 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
[Fri Aug 10 02:59:49.076329 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]     self._wrapped = Settings(settings_module)
[Fri Aug 10 02:59:49.076346 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
[Fri Aug 10 02:59:49.076357 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Fri Aug 10 02:59:49.076375 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Fri Aug 10 02:59:49.076397 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Aug 10 02:59:49.076416 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Fri Aug 10 02:59:49.076435 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Fri Aug 10 02:59:49.076453 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Fri Aug 10 02:59:49.076471 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Fri Aug 10 02:59:49.076489 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Fri Aug 10 02:59:49.076508 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Fri Aug 10 02:59:49.076526 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 83, in <module>
[Fri Aug 10 02:59:49.076536 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]     'NAME': os.environ['DB_NAME'],
[Fri Aug 10 02:59:49.076553 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/os.py", line 725, in __getitem__
[Fri Aug 10 02:59:49.076584 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912]     raise KeyError(key) from None
[Fri Aug 10 02:59:49.076638 2018] [wsgi:error] [pid 15548:tid 140434326542080] [remote 192.168.56.1:60912] KeyError: 'DB_NAME'
[Fri Aug 10 03:14:51.096273 2018] [wsgi:info] [pid 15548:tid 140434452752256] mod_wsgi (pid=15548): Shutdown requested 'takemeds.com'.
[Fri Aug 10 03:14:51.096475 2018] [wsgi:info] [pid 15548:tid 140434452752256] mod_wsgi (pid=15548): Stopping process 'takemeds.com'.
[Fri Aug 10 03:14:51.096507 2018] [wsgi:info] [pid 15548:tid 140434452752256] mod_wsgi (pid=15548): Destroying interpreters.
[Fri Aug 10 03:14:51.096533 2018] [wsgi:info] [pid 15548:tid 140434452752256] mod_wsgi (pid=15548): Cleanup interpreter ''.
[Fri Aug 10 03:14:51.097521 2018] [wsgi:info] [pid 15548:tid 140434452752256] mod_wsgi (pid=15548): Terminating Python.
[Fri Aug 10 03:14:51.165736 2018] [wsgi:info] [pid 15548:tid 140434452752256] mod_wsgi (pid=15548): Python has shutdown.
[Fri Aug 10 03:14:51.165785 2018] [wsgi:info] [pid 15548:tid 140434452752256] mod_wsgi (pid=15548): Exiting process 'takemeds.com'.
[Fri Aug 10 03:14:52.282920 2018] [wsgi:info] [pid 15816:tid 139680208365440] mod_wsgi (pid=15816): Attach interpreter ''.
[Fri Aug 10 03:14:52.303512 2018] [wsgi:info] [pid 15816:tid 139680208365440] mod_wsgi (pid=15816): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 03:14:57.966414 2018] [wsgi:info] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256] mod_wsgi (pid=15816, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 03:14:58.496130 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256] mod_wsgi (pid=15816): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Fri Aug 10 03:14:58.496245 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256] mod_wsgi (pid=15816): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 03:14:58.500923 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256] Traceback (most recent call last):
[Fri Aug 10 03:14:58.501039 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 20, in <module>
[Fri Aug 10 03:14:58.501069 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]     application = get_wsgi_application()
[Fri Aug 10 03:14:58.501093 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Fri Aug 10 03:14:58.501105 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]     django.setup(set_prefix=False)
[Fri Aug 10 03:14:58.501125 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
[Fri Aug 10 03:14:58.501136 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Fri Aug 10 03:14:58.501155 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Fri Aug 10 03:14:58.501167 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]     self._setup(name)
[Fri Aug 10 03:14:58.501185 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
[Fri Aug 10 03:14:58.501196 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]     self._wrapped = Settings(settings_module)
[Fri Aug 10 03:14:58.501214 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
[Fri Aug 10 03:14:58.501225 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Fri Aug 10 03:14:58.501243 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Fri Aug 10 03:14:58.501253 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Aug 10 03:14:58.501300 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Fri Aug 10 03:14:58.501321 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Fri Aug 10 03:14:58.501341 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Fri Aug 10 03:14:58.501360 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Fri Aug 10 03:14:58.501379 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Fri Aug 10 03:14:58.501398 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Fri Aug 10 03:14:58.501417 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 23, in <module>
[Fri Aug 10 03:14:58.501428 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]     print (os.environ['SECRET_KEY'])
[Fri Aug 10 03:14:58.501445 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/os.py", line 725, in __getitem__
[Fri Aug 10 03:14:58.501462 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256]     raise KeyError(key) from None
[Fri Aug 10 03:14:58.501515 2018] [wsgi:error] [pid 15816:tid 139680082155264] [remote 192.168.56.1:62256] KeyError: 'SECRET_KEY'
[Fri Aug 10 03:16:44.640547 2018] [wsgi:info] [pid 15816:tid 139680208365440] mod_wsgi (pid=15816): Shutdown requested 'takemeds.com'.
[Fri Aug 10 03:16:44.640765 2018] [wsgi:info] [pid 15816:tid 139680208365440] mod_wsgi (pid=15816): Stopping process 'takemeds.com'.
[Fri Aug 10 03:16:44.640790 2018] [wsgi:info] [pid 15816:tid 139680208365440] mod_wsgi (pid=15816): Destroying interpreters.
[Fri Aug 10 03:16:44.640808 2018] [wsgi:info] [pid 15816:tid 139680208365440] mod_wsgi (pid=15816): Cleanup interpreter ''.
[Fri Aug 10 03:16:44.641913 2018] [wsgi:info] [pid 15816:tid 139680208365440] mod_wsgi (pid=15816): Terminating Python.
[Fri Aug 10 03:16:44.720034 2018] [wsgi:info] [pid 15816:tid 139680208365440] mod_wsgi (pid=15816): Python has shutdown.
[Fri Aug 10 03:16:44.720085 2018] [wsgi:info] [pid 15816:tid 139680208365440] mod_wsgi (pid=15816): Exiting process 'takemeds.com'.
[Fri Aug 10 03:16:45.849100 2018] [wsgi:info] [pid 15932:tid 139905477994368] mod_wsgi (pid=15932): Attach interpreter ''.
[Fri Aug 10 03:16:45.874084 2018] [wsgi:info] [pid 15932:tid 139905477994368] mod_wsgi (pid=15932): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 03:16:51.640526 2018] [wsgi:info] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412] mod_wsgi (pid=15932, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 03:16:52.176402 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412] mod_wsgi (pid=15932): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Fri Aug 10 03:16:52.176530 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412] mod_wsgi (pid=15932): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 03:16:52.180599 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412] Traceback (most recent call last):
[Fri Aug 10 03:16:52.180704 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 20, in <module>
[Fri Aug 10 03:16:52.180721 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]     application = get_wsgi_application()
[Fri Aug 10 03:16:52.180743 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Fri Aug 10 03:16:52.180755 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]     django.setup(set_prefix=False)
[Fri Aug 10 03:16:52.180774 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
[Fri Aug 10 03:16:52.180786 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Fri Aug 10 03:16:52.180805 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Fri Aug 10 03:16:52.180816 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]     self._setup(name)
[Fri Aug 10 03:16:52.180834 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
[Fri Aug 10 03:16:52.180845 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]     self._wrapped = Settings(settings_module)
[Fri Aug 10 03:16:52.180863 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
[Fri Aug 10 03:16:52.180886 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Fri Aug 10 03:16:52.180906 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Fri Aug 10 03:16:52.180917 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Aug 10 03:16:52.180934 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Fri Aug 10 03:16:52.180952 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Fri Aug 10 03:16:52.180971 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Fri Aug 10 03:16:52.180989 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Fri Aug 10 03:16:52.181007 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Fri Aug 10 03:16:52.181026 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Fri Aug 10 03:16:52.181044 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 23, in <module>
[Fri Aug 10 03:16:52.181054 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]     print (os.environ['DB_NAME'])
[Fri Aug 10 03:16:52.181096 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/os.py", line 725, in __getitem__
[Fri Aug 10 03:16:52.181109 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412]     raise KeyError(key) from None
[Fri Aug 10 03:16:52.181159 2018] [wsgi:error] [pid 15932:tid 139905326606080] [remote 192.168.56.1:62412] KeyError: 'DB_NAME'
[Fri Aug 10 03:19:21.864941 2018] [wsgi:info] [pid 15932:tid 139905477994368] mod_wsgi (pid=15932): Shutdown requested 'takemeds.com'.
[Fri Aug 10 03:19:21.865314 2018] [wsgi:info] [pid 15932:tid 139905477994368] mod_wsgi (pid=15932): Stopping process 'takemeds.com'.
[Fri Aug 10 03:19:21.865357 2018] [wsgi:info] [pid 15932:tid 139905477994368] mod_wsgi (pid=15932): Destroying interpreters.
[Fri Aug 10 03:19:21.865382 2018] [wsgi:info] [pid 15932:tid 139905477994368] mod_wsgi (pid=15932): Cleanup interpreter ''.
[Fri Aug 10 03:19:21.867032 2018] [wsgi:info] [pid 15932:tid 139905477994368] mod_wsgi (pid=15932): Terminating Python.
[Fri Aug 10 03:19:21.952065 2018] [wsgi:info] [pid 15932:tid 139905477994368] mod_wsgi (pid=15932): Python has shutdown.
[Fri Aug 10 03:19:21.952115 2018] [wsgi:info] [pid 15932:tid 139905477994368] mod_wsgi (pid=15932): Exiting process 'takemeds.com'.
[Fri Aug 10 03:19:23.071553 2018] [wsgi:info] [pid 16074:tid 140235455108992] mod_wsgi (pid=16074): Attach interpreter ''.
[Fri Aug 10 03:19:23.090432 2018] [wsgi:info] [pid 16074:tid 140235455108992] mod_wsgi (pid=16074): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 03:19:32.138934 2018] [wsgi:info] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673] mod_wsgi (pid=16074, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 03:19:32.651543 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673] mod_wsgi (pid=16074): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Fri Aug 10 03:19:32.651655 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673] mod_wsgi (pid=16074): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 03:19:32.654260 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673] Traceback (most recent call last):
[Fri Aug 10 03:19:32.654469 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 20, in <module>
[Fri Aug 10 03:19:32.654489 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]     application = get_wsgi_application()
[Fri Aug 10 03:19:32.654521 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Fri Aug 10 03:19:32.654534 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]     django.setup(set_prefix=False)
[Fri Aug 10 03:19:32.654562 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
[Fri Aug 10 03:19:32.654577 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Fri Aug 10 03:19:32.654605 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Fri Aug 10 03:19:32.654618 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]     self._setup(name)
[Fri Aug 10 03:19:32.654644 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
[Fri Aug 10 03:19:32.654659 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]     self._wrapped = Settings(settings_module)
[Fri Aug 10 03:19:32.654685 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
[Fri Aug 10 03:19:32.654699 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Fri Aug 10 03:19:32.654727 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Fri Aug 10 03:19:32.654742 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Aug 10 03:19:32.654767 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Fri Aug 10 03:19:32.654794 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Fri Aug 10 03:19:32.654928 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Fri Aug 10 03:19:32.654959 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Fri Aug 10 03:19:32.654986 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Fri Aug 10 03:19:32.655014 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Fri Aug 10 03:19:32.655058 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 23, in <module>
[Fri Aug 10 03:19:32.655074 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]     print (os.environ['DB_NAME'])
[Fri Aug 10 03:19:32.655100 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/os.py", line 725, in __getitem__
[Fri Aug 10 03:19:32.655114 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673]     raise KeyError(key) from None
[Fri Aug 10 03:19:32.655186 2018] [wsgi:error] [pid 16074:tid 140235328898816] [remote 192.168.56.1:62673] KeyError: 'DB_NAME'
[Fri Aug 10 03:21:06.017876 2018] [wsgi:info] [pid 16074:tid 140235455108992] mod_wsgi (pid=16074): Shutdown requested 'takemeds.com'.
[Fri Aug 10 03:21:06.018150 2018] [wsgi:info] [pid 16074:tid 140235455108992] mod_wsgi (pid=16074): Stopping process 'takemeds.com'.
[Fri Aug 10 03:21:06.018178 2018] [wsgi:info] [pid 16074:tid 140235455108992] mod_wsgi (pid=16074): Destroying interpreters.
[Fri Aug 10 03:21:06.018195 2018] [wsgi:info] [pid 16074:tid 140235455108992] mod_wsgi (pid=16074): Cleanup interpreter ''.
[Fri Aug 10 03:21:06.019421 2018] [wsgi:info] [pid 16074:tid 140235455108992] mod_wsgi (pid=16074): Terminating Python.
[Fri Aug 10 03:21:06.085535 2018] [wsgi:info] [pid 16074:tid 140235455108992] mod_wsgi (pid=16074): Python has shutdown.
[Fri Aug 10 03:21:06.085584 2018] [wsgi:info] [pid 16074:tid 140235455108992] mod_wsgi (pid=16074): Exiting process 'takemeds.com'.
[Fri Aug 10 03:21:07.207638 2018] [wsgi:info] [pid 16202:tid 139841403688832] mod_wsgi (pid=16202): Attach interpreter ''.
[Fri Aug 10 03:21:07.229091 2018] [wsgi:info] [pid 16202:tid 139841403688832] mod_wsgi (pid=16202): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 03:21:13.356478 2018] [wsgi:info] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817] mod_wsgi (pid=16202, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 03:21:13.868761 2018] [wsgi:error] [pid 16202:tid 139841277478656] mo
[Fri Aug 10 03:21:13.868865 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817] mod_wsgi (pid=16202): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Fri Aug 10 03:21:13.868940 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817] mod_wsgi (pid=16202): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 03:21:13.871522 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817] Traceback (most recent call last):
[Fri Aug 10 03:21:13.871645 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 21, in <module>
[Fri Aug 10 03:21:13.871661 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]     application = get_wsgi_application()
[Fri Aug 10 03:21:13.871683 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Fri Aug 10 03:21:13.871694 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]     django.setup(set_prefix=False)
[Fri Aug 10 03:21:13.871713 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
[Fri Aug 10 03:21:13.871724 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Fri Aug 10 03:21:13.871743 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Fri Aug 10 03:21:13.871767 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]     self._setup(name)
[Fri Aug 10 03:21:13.871787 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
[Fri Aug 10 03:21:13.871798 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]     self._wrapped = Settings(settings_module)
[Fri Aug 10 03:21:13.871815 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
[Fri Aug 10 03:21:13.871826 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Fri Aug 10 03:21:13.871844 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Fri Aug 10 03:21:13.871854 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Aug 10 03:21:13.871872 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Fri Aug 10 03:21:13.871890 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Fri Aug 10 03:21:13.871909 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Fri Aug 10 03:21:13.871928 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Fri Aug 10 03:21:13.871946 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Fri Aug 10 03:21:13.871965 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Fri Aug 10 03:21:13.871984 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]   File "/home/zahlen/takemeds/takemeds/settings/settings.py", line 84, in <module>
[Fri Aug 10 03:21:13.871994 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]     'USER' : os.environ['DB_USER'],
[Fri Aug 10 03:21:13.872012 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/os.py", line 725, in __getitem__
[Fri Aug 10 03:21:13.872022 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817]     raise KeyError(key) from None
[Fri Aug 10 03:21:13.872095 2018] [wsgi:error] [pid 16202:tid 139841277478656] [remote 192.168.56.1:62817] KeyError: 'DB_USER'
[Fri Aug 10 03:28:57.227804 2018] [wsgi:info] [pid 16202:tid 139841403688832] mod_wsgi (pid=16202): Shutdown requested 'takemeds.com'.
[Fri Aug 10 03:28:57.228061 2018] [wsgi:info] [pid 16202:tid 139841403688832] mod_wsgi (pid=16202): Stopping process 'takemeds.com'.
[Fri Aug 10 03:28:57.228091 2018] [wsgi:info] [pid 16202:tid 139841403688832] mod_wsgi (pid=16202): Destroying interpreters.
[Fri Aug 10 03:28:57.228114 2018] [wsgi:info] [pid 16202:tid 139841403688832] mod_wsgi (pid=16202): Cleanup interpreter ''.
[Fri Aug 10 03:28:57.229171 2018] [wsgi:info] [pid 16202:tid 139841403688832] mod_wsgi (pid=16202): Terminating Python.
[Fri Aug 10 03:28:57.302175 2018] [wsgi:info] [pid 16202:tid 139841403688832] mod_wsgi (pid=16202): Python has shutdown.
[Fri Aug 10 03:28:57.302225 2018] [wsgi:info] [pid 16202:tid 139841403688832] mod_wsgi (pid=16202): Exiting process 'takemeds.com'.
[Fri Aug 10 03:28:58.509479 2018] [wsgi:info] [pid 16320:tid 139816312244096] mod_wsgi (pid=16320): Attach interpreter ''.
[Fri Aug 10 03:28:58.539491 2018] [wsgi:info] [pid 16320:tid 139816312244096] mod_wsgi (pid=16320): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 03:29:02.738726 2018] [wsgi:info] [pid 16320:tid 139816160855808] [remote 192.168.56.1:63486] mod_wsgi (pid=16320, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 03:29:03.235477 2018] [wsgi:error] [pid 16320:tid 139816160855808] [remote 192.168.56.1:63486] mod_wsgi (pid=16320): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Fri Aug 10 03:29:03.235589 2018] [wsgi:error] [pid 16320:tid 139816160855808] [remote 192.168.56.1:63486] mod_wsgi (pid=16320): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 03:29:03.236152 2018] [wsgi:error] [pid 16320:tid 139816160855808] [remote 192.168.56.1:63486] Traceback (most recent call last):
[Fri Aug 10 03:29:03.236202 2018] [wsgi:error] [pid 16320:tid 139816160855808] [remote 192.168.56.1:63486]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 19, in <module>
[Fri Aug 10 03:29:03.236216 2018] [wsgi:error] [pid 16320:tid 139816160855808] [remote 192.168.56.1:63486]     class WSGIEnvironment(WSGIHandler):
[Fri Aug 10 03:29:03.236286 2018] [wsgi:error] [pid 16320:tid 139816160855808] [remote 192.168.56.1:63486] NameError: name 'WSGIHandler' is not defined
[Fri Aug 10 03:29:52.606377 2018] [wsgi:info] [pid 16320:tid 139816312244096] mod_wsgi (pid=16320): Shutdown requested 'takemeds.com'.
[Fri Aug 10 03:29:52.606548 2018] [wsgi:info] [pid 16320:tid 139816312244096] mod_wsgi (pid=16320): Stopping process 'takemeds.com'.
[Fri Aug 10 03:29:52.606595 2018] [wsgi:info] [pid 16320:tid 139816312244096] mod_wsgi (pid=16320): Destroying interpreters.
[Fri Aug 10 03:29:52.606613 2018] [wsgi:info] [pid 16320:tid 139816312244096] mod_wsgi (pid=16320): Cleanup interpreter ''.
[Fri Aug 10 03:29:52.607468 2018] [wsgi:info] [pid 16320:tid 139816312244096] mod_wsgi (pid=16320): Terminating Python.
[Fri Aug 10 03:29:52.682347 2018] [wsgi:info] [pid 16320:tid 139816312244096] mod_wsgi (pid=16320): Python has shutdown.
[Fri Aug 10 03:29:52.682396 2018] [wsgi:info] [pid 16320:tid 139816312244096] mod_wsgi (pid=16320): Exiting process 'takemeds.com'.
[Fri Aug 10 03:29:53.801155 2018] [wsgi:info] [pid 16448:tid 140322020063104] mod_wsgi (pid=16448): Attach interpreter ''.
[Fri Aug 10 03:29:53.822369 2018] [wsgi:info] [pid 16448:tid 140322020063104] mod_wsgi (pid=16448): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 03:30:00.382680 2018] [wsgi:info] [pid 16448:tid 140321893852928] [remote 192.168.56.1:63568] mod_wsgi (pid=16448, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 03:30:01.046008 2018] [wsgi:error] [pid 16448:tid 140321893852928] [remote 192.168.56.1:63568] mod_wsgi (pid=16448): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Fri Aug 10 03:30:01.046142 2018] [wsgi:error] [pid 16448:tid 140321893852928] [remote 192.168.56.1:63568] mod_wsgi (pid=16448): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 03:30:01.080962 2018] [wsgi:error] [pid 16448:tid 140321893852928] [remote 192.168.56.1:63568] Traceback (most recent call last):
[Fri Aug 10 03:30:01.081105 2018] [wsgi:error] [pid 16448:tid 140321893852928] [remote 192.168.56.1:63568]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 29, in <module>
[Fri Aug 10 03:30:01.081155 2018] [wsgi:error] [pid 16448:tid 140321893852928] [remote 192.168.56.1:63568]     application = WSGIEnvironment()
[Fri Aug 10 03:30:01.081249 2018] [wsgi:error] [pid 16448:tid 140321893852928] [remote 192.168.56.1:63568]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 136, in __init__
[Fri Aug 10 03:30:01.081388 2018] [wsgi:error] [pid 16448:tid 140321893852928] [remote 192.168.56.1:63568]     self.load_middleware()
[Fri Aug 10 03:30:01.081425 2018] [wsgi:error] [pid 16448:tid 140321893852928] [remote 192.168.56.1:63568]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/handlers/base.py", line 33, in load_middleware
[Fri Aug 10 03:30:01.081440 2018] [wsgi:error] [pid 16448:tid 140321893852928] [remote 192.168.56.1:63568]     for middleware_path in reversed(settings.MIDDLEWARE):
[Fri Aug 10 03:30:01.081473 2018] [wsgi:error] [pid 16448:tid 140321893852928] [remote 192.168.56.1:63568]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Fri Aug 10 03:30:01.081496 2018] [wsgi:error] [pid 16448:tid 140321893852928] [remote 192.168.56.1:63568]     self._setup(name)
[Fri Aug 10 03:30:01.081531 2018] [wsgi:error] [pid 16448:tid 140321893852928] [remote 192.168.56.1:63568]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 42, in _setup
[Fri Aug 10 03:30:01.081561 2018] [wsgi:error] [pid 16448:tid 140321893852928] [remote 192.168.56.1:63568]     % (desc, ENVIRONMENT_VARIABLE))
[Fri Aug 10 03:30:01.081636 2018] [wsgi:error] [pid 16448:tid 140321893852928] [remote 192.168.56.1:63568] django.core.exceptions.ImproperlyConfigured: Requested setting MIDDLEWARE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
[Fri Aug 10 03:33:30.863964 2018] [wsgi:info] [pid 16448:tid 140322020063104] mod_wsgi (pid=16448): Shutdown requested 'takemeds.com'.
[Fri Aug 10 03:33:30.864347 2018] [wsgi:info] [pid 16448:tid 140322020063104] mod_wsgi (pid=16448): Stopping process 'takemeds.com'.
[Fri Aug 10 03:33:30.864389 2018] [wsgi:info] [pid 16448:tid 140322020063104] mod_wsgi (pid=16448): Destroying interpreters.
[Fri Aug 10 03:33:30.864413 2018] [wsgi:info] [pid 16448:tid 140322020063104] mod_wsgi (pid=16448): Cleanup interpreter ''.
[Fri Aug 10 03:33:30.866033 2018] [wsgi:info] [pid 16448:tid 140322020063104] mod_wsgi (pid=16448): Terminating Python.
[Fri Aug 10 03:33:30.943770 2018] [wsgi:info] [pid 16448:tid 140322020063104] mod_wsgi (pid=16448): Python has shutdown.
[Fri Aug 10 03:33:30.943826 2018] [wsgi:info] [pid 16448:tid 140322020063104] mod_wsgi (pid=16448): Exiting process 'takemeds.com'.
[Fri Aug 10 03:33:32.086561 2018] [wsgi:info] [pid 16566:tid 140330991466368] mod_wsgi (pid=16566): Attach interpreter ''.
[Fri Aug 10 03:33:32.104244 2018] [wsgi:info] [pid 16566:tid 140330991466368] mod_wsgi (pid=16566): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 03:33:38.523118 2018] [wsgi:info] [pid 16566:tid 140330865256192] [remote 192.168.56.1:63881] mod_wsgi (pid=16566, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 03:33:39.112007 2018] [wsgi:error] [pid 16566:tid 140330865256192] [remote 192.168.56.1:63881] mod_wsgi (pid=16566): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Fri Aug 10 03:33:39.112115 2018] [wsgi:error] [pid 16566:tid 140330865256192] [remote 192.168.56.1:63881] mod_wsgi (pid=16566): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 03:33:39.114022 2018] [wsgi:error] [pid 16566:tid 140330865256192] [remote 192.168.56.1:63881] Traceback (most recent call last):
[Fri Aug 10 03:33:39.114123 2018] [wsgi:error] [pid 16566:tid 140330865256192] [remote 192.168.56.1:63881]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 27, in <module>
[Fri Aug 10 03:33:39.114200 2018] [wsgi:error] [pid 16566:tid 140330865256192] [remote 192.168.56.1:63881]     application = WSGIEnvironment()
[Fri Aug 10 03:33:39.114233 2018] [wsgi:error] [pid 16566:tid 140330865256192] [remote 192.168.56.1:63881]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 136, in __init__
[Fri Aug 10 03:33:39.114263 2018] [wsgi:error] [pid 16566:tid 140330865256192] [remote 192.168.56.1:63881]     self.load_middleware()
[Fri Aug 10 03:33:39.114347 2018] [wsgi:error] [pid 16566:tid 140330865256192] [remote 192.168.56.1:63881]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/handlers/base.py", line 33, in load_middleware
[Fri Aug 10 03:33:39.114374 2018] [wsgi:error] [pid 16566:tid 140330865256192] [remote 192.168.56.1:63881]     for middleware_path in reversed(settings.MIDDLEWARE):
[Fri Aug 10 03:33:39.114409 2018] [wsgi:error] [pid 16566:tid 140330865256192] [remote 192.168.56.1:63881]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Fri Aug 10 03:33:39.114429 2018] [wsgi:error] [pid 16566:tid 140330865256192] [remote 192.168.56.1:63881]     self._setup(name)
[Fri Aug 10 03:33:39.114460 2018] [wsgi:error] [pid 16566:tid 140330865256192] [remote 192.168.56.1:63881]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 42, in _setup
[Fri Aug 10 03:33:39.114477 2018] [wsgi:error] [pid 16566:tid 140330865256192] [remote 192.168.56.1:63881]     % (desc, ENVIRONMENT_VARIABLE))
[Fri Aug 10 03:33:39.114559 2018] [wsgi:error] [pid 16566:tid 140330865256192] [remote 192.168.56.1:63881] django.core.exceptions.ImproperlyConfigured: Requested setting MIDDLEWARE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
[Fri Aug 10 03:44:58.537297 2018] [wsgi:info] [pid 1278:tid 140357650147200] mod_wsgi (pid=1278): Attach interpreter ''.
[Fri Aug 10 03:44:58.716225 2018] [wsgi:info] [pid 1278:tid 140357650147200] mod_wsgi (pid=1278): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 03:48:03.469916 2018] [wsgi:info] [pid 1278:tid 140357650147200] mod_wsgi (pid=1278): Shutdown requested 'takemeds.com'.
[Fri Aug 10 03:48:03.470088 2018] [wsgi:info] [pid 1278:tid 140357650147200] mod_wsgi (pid=1278): Stopping process 'takemeds.com'.
[Fri Aug 10 03:48:03.470108 2018] [wsgi:info] [pid 1278:tid 140357650147200] mod_wsgi (pid=1278): Destroying interpreters.
[Fri Aug 10 03:48:03.470119 2018] [wsgi:info] [pid 1278:tid 140357650147200] mod_wsgi (pid=1278): Cleanup interpreter ''.
[Fri Aug 10 03:48:03.480454 2018] [wsgi:info] [pid 1278:tid 140357650147200] mod_wsgi (pid=1278): Terminating Python.
[Fri Aug 10 03:48:03.489208 2018] [wsgi:info] [pid 1278:tid 140357650147200] mod_wsgi (pid=1278): Python has shutdown.
[Fri Aug 10 03:48:03.489251 2018] [wsgi:info] [pid 1278:tid 140357650147200] mod_wsgi (pid=1278): Exiting process 'takemeds.com'.
[Fri Aug 10 03:48:04.656802 2018] [wsgi:info] [pid 1622:tid 140393062639488] mod_wsgi (pid=1622): Attach interpreter ''.
[Fri Aug 10 03:48:04.673031 2018] [wsgi:info] [pid 1622:tid 140393062639488] mod_wsgi (pid=1622): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 03:48:08.872843 2018] [wsgi:info] [pid 1622:tid 140392936429312] [remote 192.168.56.1:65063] mod_wsgi (pid=1622, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 03:48:13.417257 2018] [wsgi:error] [pid 1622:tid 140392936429312] [remote 192.168.56.1:65063] mod_wsgi (pid=1622): Target WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py' cannot be loaded as Python module.
[Fri Aug 10 03:48:13.417382 2018] [wsgi:error] [pid 1622:tid 140392936429312] [remote 192.168.56.1:65063] mod_wsgi (pid=1622): Exception occurred processing WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 03:48:13.429714 2018] [wsgi:error] [pid 1622:tid 140392936429312] [remote 192.168.56.1:65063] Traceback (most recent call last):
[Fri Aug 10 03:48:13.429834 2018] [wsgi:error] [pid 1622:tid 140392936429312] [remote 192.168.56.1:65063]   File "/home/zahlen/takemeds/takemeds/wsgi.py", line 14, in <module>
[Fri Aug 10 03:48:13.429853 2018] [wsgi:error] [pid 1622:tid 140392936429312] [remote 192.168.56.1:65063]     print (os.environ['DB_NAME'])
[Fri Aug 10 03:48:13.429895 2018] [wsgi:error] [pid 1622:tid 140392936429312] [remote 192.168.56.1:65063]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/os.py", line 725, in __getitem__
[Fri Aug 10 03:48:13.429908 2018] [wsgi:error] [pid 1622:tid 140392936429312] [remote 192.168.56.1:65063]     raise KeyError(key) from None
[Fri Aug 10 03:48:13.429963 2018] [wsgi:error] [pid 1622:tid 140392936429312] [remote 192.168.56.1:65063] KeyError: 'DB_NAME'
[Fri Aug 10 13:41:08.182121 2018] [wsgi:info] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502] mod_wsgi (pid=1622, process='takemeds.com', application=''): Loading WSGI script '/home/zahlen/takemeds/takemeds/wsgi.py'.
[Fri Aug 10 13:41:08.192355 2018] [wsgi:error] [pid 1622:tid 140392944822016] be=xjlegqlgf%=ncszino&4m6tar)x6(w$r2qv@&k#t+o+pi9z
[Fri Aug 10 08:11:09.451808 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502] Session data corrupted
[Fri Aug 10 08:11:09.628568 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502] Internal Server Error: /
[Fri Aug 10 08:11:09.628616 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502] Traceback (most recent call last):
[Fri Aug 10 08:11:09.628630 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
[Fri Aug 10 08:11:09.628640 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]     response = get_response(request)
[Fri Aug 10 08:11:09.628649 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/handlers/base.py", line 111, in _get_response
[Fri Aug 10 08:11:09.628658 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]     resolver_match = resolver.resolve(request.path_info)
[Fri Aug 10 08:11:09.628667 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/urls/resolvers.py", line 491, in resolve
[Fri Aug 10 08:11:09.628676 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]     for pattern in self.url_patterns:
[Fri Aug 10 08:11:09.628687 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/utils/functional.py", line 37, in __get__
[Fri Aug 10 08:11:09.628700 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]     res = instance.__dict__[self.name] = self.func(instance)
[Fri Aug 10 08:11:09.628712 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/urls/resolvers.py", line 533, in url_patterns
[Fri Aug 10 08:11:09.628722 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
[Fri Aug 10 08:11:09.628731 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/utils/functional.py", line 37, in __get__
[Fri Aug 10 08:11:09.628740 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]     res = instance.__dict__[self.name] = self.func(instance)
[Fri Aug 10 08:11:09.628749 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
[Fri Aug 10 08:11:09.628758 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]     return import_module(self.urlconf_name)
[Fri Aug 10 08:11:09.628767 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Fri Aug 10 08:11:09.628794 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Aug 10 08:11:09.628805 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Fri Aug 10 08:11:09.628813 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Fri Aug 10 08:11:09.628822 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Fri Aug 10 08:11:09.628830 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Fri Aug 10 08:11:09.628839 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Fri Aug 10 08:11:09.628849 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Fri Aug 10 08:11:09.628861 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "/home/zahlen/takemeds/takemeds/urls.py", line 23, in <module>
[Fri Aug 10 08:11:09.628872 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]     url(r'^search/',include('places.urls')),
[Fri Aug 10 08:11:09.628880 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/urls/conf.py", line 34, in include
[Fri Aug 10 08:11:09.628889 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]     urlconf_module = import_module(urlconf_module)
[Fri Aug 10 08:11:09.628897 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Fri Aug 10 08:11:09.628905 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Aug 10 08:11:09.628941 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Fri Aug 10 08:11:09.628954 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Fri Aug 10 08:11:09.628963 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Fri Aug 10 08:11:09.628971 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Fri Aug 10 08:11:09.628979 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Fri Aug 10 08:11:09.628988 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Fri Aug 10 08:11:09.628997 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "/home/zahlen/takemeds/places/urls.py", line 2, in <module>
[Fri Aug 10 08:11:09.629009 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]     from . import views
[Fri Aug 10 08:11:09.629021 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "/home/zahlen/takemeds/places/views.py", line 13, in <module>
[Fri Aug 10 08:11:09.629030 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]     database = MySQLdb.connect(user = os.environ['DB_USER'] , passwd = os.environ['DB_PASS'] , db = os.environ['DB_NAME'])
[Fri Aug 10 08:11:09.629047 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/os.py", line 725, in __getitem__
[Fri Aug 10 08:11:09.629056 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502]     raise KeyError(key) from None
[Fri Aug 10 08:11:09.629068 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502] KeyError: 'DB_USER'
[Fri Aug 10 08:11:09.629087 2018] [wsgi:error] [pid 1622:tid 140392944822016] [remote 192.168.56.1:19502] 
[Fri Aug 10 08:27:15.370785 2018] [wsgi:info] [pid 1622:tid 140393062639488] mod_wsgi (pid=1622): Shutdown requested 'takemeds.com'.
[Fri Aug 10 08:27:15.371120 2018] [wsgi:info] [pid 1622:tid 140393062639488] mod_wsgi (pid=1622): Stopping process 'takemeds.com'.
[Fri Aug 10 08:27:15.371158 2018] [wsgi:info] [pid 1622:tid 140393062639488] mod_wsgi (pid=1622): Destroying interpreters.
[Fri Aug 10 08:27:15.371233 2018] [wsgi:info] [pid 1622:tid 140393062639488] mod_wsgi (pid=1622): Cleanup interpreter ''.
[Fri Aug 10 08:27:15.371809 2018] [wsgi:info] [pid 1622:tid 140393062639488] mod_wsgi (pid=1622): Terminating Python.
[Fri Aug 10 08:27:15.464759 2018] [wsgi:info] [pid 1622:tid 140393062639488] mod_wsgi (pid=1622): Python has shutdown.
[Fri Aug 10 08:27:15.464805 2018] [wsgi:info] [pid 1622:tid 140393062639488] mod_wsgi (pid=1622): Exiting process 'takemeds.com'.
[Fri Aug 10 13:57:16.727644 2018] [wsgi:info] [pid 2341:tid 140098836756352] mod_wsgi (pid=2341): Attach interpreter ''.
[Fri Aug 10 13:57:16.748082 2018] [wsgi:info] [pid 2341:tid 140098836756352] mod_wsgi (pid=2341): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 13:57:21.129404 2018] [wsgi:info] [pid 2341:tid 140098710546176] [remote 192.168.56.1:20888] mod_wsgi (pid=2341, process='takemeds.com', application=''): Loading WSGI script '/etc/prod_wsgi.py'.
[Fri Aug 10 13:57:21.593707 2018] [wsgi:error] [pid 2341:tid 140098710546176] h8co4)8-=(2x=w#h+t10+b3ugq1jw2o+3=uip-mcd(v%m3t%ny
[Fri Aug 10 08:28:09.775740 2018] [wsgi:error] [pid 2341:tid 140098710546176] [remote 192.168.56.1:20956] Brand
[Fri Aug 10 09:06:31.486424 2018] [wsgi:info] [pid 2341:tid 140098836756352] mod_wsgi (pid=2341): Shutdown requested 'takemeds.com'.
[Fri Aug 10 09:06:31.486779 2018] [wsgi:info] [pid 2341:tid 140098836756352] mod_wsgi (pid=2341): Stopping process 'takemeds.com'.
[Fri Aug 10 09:06:31.486819 2018] [wsgi:info] [pid 2341:tid 140098836756352] mod_wsgi (pid=2341): Destroying interpreters.
[Fri Aug 10 09:06:31.486843 2018] [wsgi:info] [pid 2341:tid 140098836756352] mod_wsgi (pid=2341): Cleanup interpreter ''.
[Fri Aug 10 09:06:31.487679 2018] [wsgi:info] [pid 2341:tid 140098836756352] mod_wsgi (pid=2341): Terminating Python.
[Fri Aug 10 09:06:31.599381 2018] [wsgi:info] [pid 2341:tid 140098836756352] mod_wsgi (pid=2341): Python has shutdown.
[Fri Aug 10 09:06:31.599445 2018] [wsgi:info] [pid 2341:tid 140098836756352] mod_wsgi (pid=2341): Exiting process 'takemeds.com'.
[Fri Aug 10 14:36:32.751483 2018] [wsgi:info] [pid 2605:tid 140715785103232] mod_wsgi (pid=2605): Attach interpreter ''.
[Fri Aug 10 14:36:32.768057 2018] [wsgi:info] [pid 2605:tid 140715785103232] mod_wsgi (pid=2605): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 14:36:38.045656 2018] [wsgi:info] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304] mod_wsgi (pid=2605, process='takemeds.com', application=''): Loading WSGI script '/etc/prod_wsgi.py'.
[Fri Aug 10 14:36:38.548131 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304] mod_wsgi (pid=2605): Target WSGI script '/etc/prod_wsgi.py' cannot be loaded as Python module.
[Fri Aug 10 14:36:38.548214 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304] mod_wsgi (pid=2605): Exception occurred processing WSGI script '/etc/prod_wsgi.py'.
[Fri Aug 10 14:36:38.629944 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304] Traceback (most recent call last):
[Fri Aug 10 14:36:38.630149 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]   File "/etc/prod_wsgi.py", line 23, in <module>
[Fri Aug 10 14:36:38.630174 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]     application = get_wsgi_application()
[Fri Aug 10 14:36:38.630439 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Fri Aug 10 14:36:38.630468 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]     django.setup(set_prefix=False)
[Fri Aug 10 14:36:38.630510 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
[Fri Aug 10 14:36:38.630528 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Fri Aug 10 14:36:38.630557 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Fri Aug 10 14:36:38.630574 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]     self._setup(name)
[Fri Aug 10 14:36:38.630603 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
[Fri Aug 10 14:36:38.630619 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]     self._wrapped = Settings(settings_module)
[Fri Aug 10 14:36:38.630647 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 107, in __init__
[Fri Aug 10 14:36:38.630664 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Fri Aug 10 14:36:38.630692 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Fri Aug 10 14:36:38.630709 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]     return _bootstrap._gcd_import(name[level:], package, level)
[Fri Aug 10 14:36:38.630751 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Fri Aug 10 14:36:38.630783 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Fri Aug 10 14:36:38.630852 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
[Fri Aug 10 14:36:38.630883 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[Fri Aug 10 14:36:38.630915 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[Fri Aug 10 14:36:38.630959 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Fri Aug 10 14:36:38.631005 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]   File "/home/zahlen/takemeds/takemeds/settings/prod_settings.py", line 5, in <module>
[Fri Aug 10 14:36:38.631032 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304]     DEBUG = FALSE
[Fri Aug 10 14:36:38.631174 2018] [wsgi:error] [pid 2605:tid 140715658893056] [remote 192.168.56.1:24304] NameError: name 'FALSE' is not defined
[Fri Aug 10 14:37:47.802735 2018] [wsgi:info] [pid 2605:tid 140715785103232] mod_wsgi (pid=2605): Shutdown requested 'takemeds.com'.
[Fri Aug 10 14:37:47.803097 2018] [wsgi:info] [pid 2605:tid 140715785103232] mod_wsgi (pid=2605): Stopping process 'takemeds.com'.
[Fri Aug 10 14:37:47.803138 2018] [wsgi:info] [pid 2605:tid 140715785103232] mod_wsgi (pid=2605): Destroying interpreters.
[Fri Aug 10 14:37:47.803172 2018] [wsgi:info] [pid 2605:tid 140715785103232] mod_wsgi (pid=2605): Cleanup interpreter ''.
[Fri Aug 10 14:37:47.805140 2018] [wsgi:info] [pid 2605:tid 140715785103232] mod_wsgi (pid=2605): Terminating Python.
[Fri Aug 10 14:37:47.884706 2018] [wsgi:info] [pid 2605:tid 140715785103232] mod_wsgi (pid=2605): Python has shutdown.
[Fri Aug 10 14:37:47.884750 2018] [wsgi:info] [pid 2605:tid 140715785103232] mod_wsgi (pid=2605): Exiting process 'takemeds.com'.
[Fri Aug 10 14:37:49.080238 2018] [wsgi:info] [pid 2728:tid 140428493526912] mod_wsgi (pid=2728): Attach interpreter ''.
[Fri Aug 10 14:37:49.097587 2018] [wsgi:info] [pid 2728:tid 140428493526912] mod_wsgi (pid=2728): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 14:37:53.572598 2018] [wsgi:info] [pid 2728:tid 140428367316736] [remote 192.168.56.1:24414] mod_wsgi (pid=2728, process='takemeds.com', application=''): Loading WSGI script '/etc/prod_wsgi.py'.
[Fri Aug 10 14:37:54.085173 2018] [wsgi:error] [pid 2728:tid 140428367316736] [remote 192.168.56.1:24414] mod_wsgi (pid=2728): Target WSGI script '/etc/prod_wsgi.py' cannot be loaded as Python module.
[Fri Aug 10 14:37:54.085342 2018] [wsgi:error] [pid 2728:tid 140428367316736] [remote 192.168.56.1:24414] mod_wsgi (pid=2728): Exception occurred processing WSGI script '/etc/prod_wsgi.py'.
[Fri Aug 10 14:37:54.086592 2018] [wsgi:error] [pid 2728:tid 140428367316736] [remote 192.168.56.1:24414] Traceback (most recent call last):
[Fri Aug 10 14:37:54.086660 2018] [wsgi:error] [pid 2728:tid 140428367316736] [remote 192.168.56.1:24414]   File "/etc/prod_wsgi.py", line 23, in <module>
[Fri Aug 10 14:37:54.086675 2018] [wsgi:error] [pid 2728:tid 140428367316736] [remote 192.168.56.1:24414]     application = get_wsgi_application()
[Fri Aug 10 14:37:54.086695 2018] [wsgi:error] [pid 2728:tid 140428367316736] [remote 192.168.56.1:24414]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Fri Aug 10 14:37:54.086706 2018] [wsgi:error] [pid 2728:tid 140428367316736] [remote 192.168.56.1:24414]     django.setup(set_prefix=False)
[Fri Aug 10 14:37:54.086751 2018] [wsgi:error] [pid 2728:tid 140428367316736] [remote 192.168.56.1:24414]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
[Fri Aug 10 14:37:54.086765 2018] [wsgi:error] [pid 2728:tid 140428367316736] [remote 192.168.56.1:24414]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Fri Aug 10 14:37:54.086783 2018] [wsgi:error] [pid 2728:tid 140428367316736] [remote 192.168.56.1:24414]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
[Fri Aug 10 14:37:54.086794 2018] [wsgi:error] [pid 2728:tid 140428367316736] [remote 192.168.56.1:24414]     self._setup(name)
[Fri Aug 10 14:37:54.086811 2018] [wsgi:error] [pid 2728:tid 140428367316736] [remote 192.168.56.1:24414]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
[Fri Aug 10 14:37:54.086821 2018] [wsgi:error] [pid 2728:tid 140428367316736] [remote 192.168.56.1:24414]     self._wrapped = Settings(settings_module)
[Fri Aug 10 14:37:54.086839 2018] [wsgi:error] [pid 2728:tid 140428367316736] [remote 192.168.56.1:24414]   File "/home/zahlen/.virtualenvs/takemeds/lib/python3.5/site-packages/django/conf/__init__.py", line 126, in __init__
[Fri Aug 10 14:37:54.086850 2018] [wsgi:error] [pid 2728:tid 140428367316736] [remote 192.168.56.1:24414]     raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
[Fri Aug 10 14:37:54.086909 2018] [wsgi:error] [pid 2728:tid 140428367316736] [remote 192.168.56.1:24414] django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
[Fri Aug 10 14:39:22.800933 2018] [wsgi:info] [pid 2728:tid 140428493526912] mod_wsgi (pid=2728): Shutdown requested 'takemeds.com'.
[Fri Aug 10 14:39:22.801303 2018] [wsgi:info] [pid 2728:tid 140428493526912] mod_wsgi (pid=2728): Stopping process 'takemeds.com'.
[Fri Aug 10 14:39:22.801344 2018] [wsgi:info] [pid 2728:tid 140428493526912] mod_wsgi (pid=2728): Destroying interpreters.
[Fri Aug 10 14:39:22.801368 2018] [wsgi:info] [pid 2728:tid 140428493526912] mod_wsgi (pid=2728): Cleanup interpreter ''.
[Fri Aug 10 14:39:22.803580 2018] [wsgi:info] [pid 2728:tid 140428493526912] mod_wsgi (pid=2728): Terminating Python.
[Fri Aug 10 14:39:22.919304 2018] [wsgi:info] [pid 2728:tid 140428493526912] mod_wsgi (pid=2728): Python has shutdown.
[Fri Aug 10 14:39:22.919358 2018] [wsgi:info] [pid 2728:tid 140428493526912] mod_wsgi (pid=2728): Exiting process 'takemeds.com'.
[Fri Aug 10 14:39:24.226844 2018] [wsgi:info] [pid 2892:tid 140537711499136] mod_wsgi (pid=2892): Attach interpreter ''.
[Fri Aug 10 14:39:24.249609 2018] [wsgi:info] [pid 2892:tid 140537711499136] mod_wsgi (pid=2892): Adding '/home/zahlen/takemeds' to path.
[Fri Aug 10 14:39:27.387806 2018] [wsgi:info] [pid 2892:tid 140537585288960] [remote 192.168.56.1:24547] mod_wsgi (pid=2892, process='takemeds.com', application=''): Loading WSGI script '/etc/prod_wsgi.py'.
[Sat Oct 27 21:43:06.311616 2018] [wsgi:info] [pid 2892:tid 140537711499136] mod_wsgi (pid=2892): Shutdown requested 'takemeds.com'.
[Sat Oct 27 21:43:06.412311 2018] [wsgi:info] [pid 2892:tid 140537711499136] mod_wsgi (pid=2892): Stopping process 'takemeds.com'.
[Sat Oct 27 21:43:06.419667 2018] [wsgi:info] [pid 2892:tid 140537711499136] mod_wsgi (pid=2892): Destroying interpreters.
[Sat Oct 27 21:43:06.419718 2018] [wsgi:info] [pid 2892:tid 140537711499136] mod_wsgi (pid=2892): Cleanup interpreter ''.
[Sat Oct 27 21:43:06.609919 2018] [wsgi:info] [pid 2892:tid 140537711499136] mod_wsgi (pid=2892): Terminating Python.
[Sat Oct 27 21:43:07.741543 2018] [wsgi:info] [pid 2892:tid 140537711499136] mod_wsgi (pid=2892): Python has shutdown.
[Sat Oct 27 21:43:07.741619 2018] [wsgi:info] [pid 2892:tid 140537711499136] mod_wsgi (pid=2892): Exiting process 'takemeds.com'.
[Sun Oct 28 03:13:19.573602 2018] [wsgi:info] [pid 1311:tid 139736738215808] mod_wsgi (pid=1311): Attach interpreter ''.
[Sun Oct 28 03:13:19.976125 2018] [wsgi:info] [pid 1311:tid 139736738215808] mod_wsgi (pid=1311): Adding '/home/zahlen/takemeds' to path.
[Sun Oct 28 06:25:04.436024 2018] [wsgi:info] [pid 1311:tid 139736738215808] mod_wsgi (pid=1311): Shutdown requested 'takemeds.com'.
[Sun Oct 28 06:25:04.436853 2018] [wsgi:info] [pid 1311:tid 139736738215808] mod_wsgi (pid=1311): Stopping process 'takemeds.com'.
[Sun Oct 28 06:25:04.436875 2018] [wsgi:info] [pid 1311:tid 139736738215808] mod_wsgi (pid=1311): Destroying interpreters.
[Sun Oct 28 06:25:04.436887 2018] [wsgi:info] [pid 1311:tid 139736738215808] mod_wsgi (pid=1311): Cleanup interpreter ''.
[Sun Oct 28 06:25:04.775454 2018] [wsgi:info] [pid 1311:tid 139736738215808] mod_wsgi (pid=1311): Terminating Python.
[Sun Oct 28 06:25:04.817806 2018] [wsgi:info] [pid 1311:tid 139736738215808] mod_wsgi (pid=1311): Python has shutdown.
[Sun Oct 28 06:25:04.817845 2018] [wsgi:info] [pid 1311:tid 139736738215808] mod_wsgi (pid=1311): Exiting process 'takemeds.com'.
[Sun Oct 28 06:25:05.544063 2018] [wsgi:info] [pid 7930:tid 139736738215808] mod_wsgi (pid=7930): Attach interpreter ''.
[Sun Oct 28 06:25:05.595527 2018] [wsgi:info] [pid 7930:tid 139736738215808] mod_wsgi (pid=7930): Adding '/home/zahlen/takemeds' to path.
[Thu Nov 22 10:25:21.674268 2018] [wsgi:info] [pid 1326:tid 140587434211200] mod_wsgi (pid=1326): Attach interpreter ''.
[Thu Nov 22 10:25:22.019677 2018] [wsgi:info] [pid 1326:tid 140587434211200] mod_wsgi (pid=1326): Adding '/home/zahlen/takemeds' to path.
[Sun Nov 25 17:14:40.559070 2018] [wsgi:info] [pid 1366:tid 139858918643584] mod_wsgi (pid=1366): Attach interpreter ''.
[Sun Nov 25 17:14:40.942073 2018] [wsgi:info] [pid 1366:tid 139858918643584] mod_wsgi (pid=1366): Adding '/home/zahlen/takemeds' to path.
[Mon Nov 26 00:11:52.122756 2018] [wsgi:info] [pid 1366:tid 139858918643584] mod_wsgi (pid=1366): Shutdown requested 'takemeds.com'.
[Mon Nov 26 00:11:52.146598 2018] [wsgi:info] [pid 1366:tid 139858918643584] mod_wsgi (pid=1366): Stopping process 'takemeds.com'.
[Mon Nov 26 00:11:52.148071 2018] [wsgi:info] [pid 1366:tid 139858918643584] mod_wsgi (pid=1366): Destroying interpreters.
[Mon Nov 26 00:11:52.148106 2018] [wsgi:info] [pid 1366:tid 139858918643584] mod_wsgi (pid=1366): Cleanup interpreter ''.
[Mon Nov 26 00:11:52.271705 2018] [wsgi:info] [pid 1366:tid 139858918643584] mod_wsgi (pid=1366): Terminating Python.
[Mon Nov 26 00:11:52.293108 2018] [wsgi:info] [pid 1366:tid 139858918643584] mod_wsgi (pid=1366): Python has shutdown.
[Mon Nov 26 00:11:52.293153 2018] [wsgi:info] [pid 1366:tid 139858918643584] mod_wsgi (pid=1366): Exiting process 'takemeds.com'.
[Mon Nov 26 00:12:04.418143 2018] [wsgi:info] [pid 1310:tid 140357598947200] mod_wsgi (pid=1310): Attach interpreter ''.
[Mon Nov 26 00:12:05.745795 2018] [wsgi:info] [pid 1310:tid 140357598947200] mod_wsgi (pid=1310): Adding '/home/zahlen/takemeds' to path.
[Sun Dec 16 15:22:14.995215 2018] [wsgi:info] [pid 1310:tid 140357598947200] mod_wsgi (pid=1310): Shutdown requested 'takemeds.com'.
[Sun Dec 16 15:22:15.032612 2018] [wsgi:info] [pid 1310:tid 140357598947200] mod_wsgi (pid=1310): Stopping process 'takemeds.com'.
[Sun Dec 16 15:22:15.032691 2018] [wsgi:info] [pid 1310:tid 140357598947200] mod_wsgi (pid=1310): Destroying interpreters.
[Sun Dec 16 15:22:15.032718 2018] [wsgi:info] [pid 1310:tid 140357598947200] mod_wsgi (pid=1310): Cleanup interpreter ''.
[Sun Dec 16 15:22:15.225357 2018] [wsgi:info] [pid 1310:tid 140357598947200] mod_wsgi (pid=1310): Terminating Python.
[Sun Dec 16 15:22:15.244960 2018] [wsgi:info] [pid 1310:tid 140357598947200] mod_wsgi (pid=1310): Python has shutdown.
[Sun Dec 16 15:22:15.245002 2018] [wsgi:info] [pid 1310:tid 140357598947200] mod_wsgi (pid=1310): Exiting process 'takemeds.com'.
[Sun Dec 16 15:22:17.209898 2018] [wsgi:info] [pid 3252:tid 139991295686528] mod_wsgi (pid=3252): Attach interpreter ''.
[Sun Dec 16 15:22:17.495171 2018] [wsgi:info] [pid 3252:tid 139991295686528] mod_wsgi (pid=3252): Adding '/home/zahlen/takemeds' to path.
[Sun Dec 16 15:39:33.211439 2018] [wsgi:info] [pid 3252:tid 139991176754944] [remote 192.168.56.1:59151] mod_wsgi (pid=3252, process='takemeds.com', application=''): Loading WSGI script '/etc/prod_wsgi.py'.
[Sun Dec 16 10:10:53.774038 2018] [wsgi:error] [pid 3252:tid 139991176754944] [remote 192.168.56.1:59170] Brand
[Thu Jan 10 16:48:33.482135 2019] [wsgi:info] [pid 3252:tid 139991295686528] mod_wsgi (pid=3252): Shutdown requested 'takemeds.com'.
[Thu Jan 10 16:48:33.484948 2019] [wsgi:info] [pid 3252:tid 139991295686528] mod_wsgi (pid=3252): Stopping process 'takemeds.com'.
[Thu Jan 10 16:48:33.484978 2019] [wsgi:info] [pid 3252:tid 139991295686528] mod_wsgi (pid=3252): Destroying interpreters.
[Thu Jan 10 16:48:33.484992 2019] [wsgi:info] [pid 3252:tid 139991295686528] mod_wsgi (pid=3252): Cleanup interpreter ''.
[Thu Jan 10 16:48:33.485440 2019] [wsgi:info] [pid 3252:tid 139991295686528] mod_wsgi (pid=3252): Terminating Python.
[Thu Jan 10 16:48:33.655141 2019] [wsgi:info] [pid 3252:tid 139991295686528] mod_wsgi (pid=3252): Python has shutdown.
[Thu Jan 10 16:48:33.655390 2019] [wsgi:info] [pid 3252:tid 139991295686528] mod_wsgi (pid=3252): Exiting process 'takemeds.com'.
[Thu Jan 10 22:18:52.155448 2019] [wsgi:info] [pid 1380:tid 139884525184896] mod_wsgi (pid=1380): Attach interpreter ''.
[Thu Jan 10 22:18:53.591704 2019] [wsgi:info] [pid 1380:tid 139884525184896] mod_wsgi (pid=1380): Adding '/home/zahlen/takemeds' to path.
[Sat Mar 23 18:24:09.227164 2019] [wsgi:info] [pid 1263:tid 140567898527616] mod_wsgi (pid=1263): Attach interpreter ''.
[Sat Mar 23 18:24:09.577365 2019] [wsgi:info] [pid 1263:tid 140567898527616] mod_wsgi (pid=1263): Adding '/home/zahlen/takemeds' to path.
[Sun Mar 24 15:47:19.046036 2019] [wsgi:info] [pid 1334:tid 140471211415424] mod_wsgi (pid=1334): Attach interpreter ''.
[Sun Mar 24 15:47:20.133541 2019] [wsgi:info] [pid 1334:tid 140471211415424] mod_wsgi (pid=1334): Adding '/home/zahlen/takemeds' to path.
[Sun Mar 24 15:55:54.864233 2019] [wsgi:info] [pid 1334:tid 140471085201152] [remote 192.168.60.1:50184] mod_wsgi (pid=1334, process='takemeds.com', application=''): Loading WSGI script '/etc/prod_wsgi.py'.
[Sun Mar 24 10:28:08.043008 2019] [wsgi:info] [pid 1334:tid 140471211415424] mod_wsgi (pid=1334): Shutdown requested 'takemeds.com'.
[Sun Mar 24 10:28:08.044551 2019] [wsgi:info] [pid 1334:tid 140471211415424] mod_wsgi (pid=1334): Stopping process 'takemeds.com'.
[Sun Mar 24 10:28:08.044589 2019] [wsgi:info] [pid 1334:tid 140471211415424] mod_wsgi (pid=1334): Destroying interpreters.
[Sun Mar 24 10:28:08.044603 2019] [wsgi:info] [pid 1334:tid 140471211415424] mod_wsgi (pid=1334): Cleanup interpreter ''.
[Sun Mar 24 10:28:08.048927 2019] [wsgi:info] [pid 1334:tid 140471211415424] mod_wsgi (pid=1334): Terminating Python.
[Sun Mar 24 10:28:08.188876 2019] [wsgi:info] [pid 1334:tid 140471211415424] mod_wsgi (pid=1334): Python has shutdown.
[Sun Mar 24 10:28:08.188918 2019] [wsgi:info] [pid 1334:tid 140471211415424] mod_wsgi (pid=1334): Exiting process 'takemeds.com'.
[Sun Mar 24 15:58:09.329626 2019] [wsgi:info] [pid 2235:tid 140712183531392] mod_wsgi (pid=2235): Attach interpreter ''.
[Sun Mar 24 15:58:09.356612 2019] [wsgi:info] [pid 2235:tid 140712183531392] mod_wsgi (pid=2235): Adding '/home/zahlen/takemeds' to path.
[Sun Mar 24 16:15:06.720235 2019] [wsgi:info] [pid 2235:tid 140712032139008] [remote 192.168.60.1:50420] mod_wsgi (pid=2235, process='takemeds.com', application=''): Loading WSGI script '/etc/prod_wsgi.py'.
[Sun Mar 24 10:57:49.241817 2019] [wsgi:info] [pid 2235:tid 140712183531392] mod_wsgi (pid=2235): Shutdown requested 'takemeds.com'.
[Sun Mar 24 10:57:49.244477 2019] [wsgi:info] [pid 2235:tid 140712183531392] mod_wsgi (pid=2235): Stopping process 'takemeds.com'.
[Sun Mar 24 10:57:49.244519 2019] [wsgi:info] [pid 2235:tid 140712183531392] mod_wsgi (pid=2235): Destroying interpreters.
[Sun Mar 24 10:57:49.244541 2019] [wsgi:info] [pid 2235:tid 140712183531392] mod_wsgi (pid=2235): Cleanup interpreter ''.
[Sun Mar 24 10:57:49.246887 2019] [wsgi:info] [pid 2235:tid 140712183531392] mod_wsgi (pid=2235): Terminating Python.
[Sun Mar 24 10:57:49.372063 2019] [wsgi:info] [pid 2235:tid 140712183531392] mod_wsgi (pid=2235): Python has shutdown.
[Sun Mar 24 10:57:49.372292 2019] [wsgi:info] [pid 2235:tid 140712183531392] mod_wsgi (pid=2235): Exiting process 'takemeds.com'.
[Sun Mar 24 16:27:50.473669 2019] [wsgi:info] [pid 5654:tid 139734294390656] mod_wsgi (pid=5654): Attach interpreter ''.
[Sun Mar 24 16:27:50.500201 2019] [wsgi:info] [pid 5654:tid 139734294390656] mod_wsgi (pid=5654): Adding '/home/zahlen/takemeds' to path.
[Sun Mar 24 16:27:59.347842 2019] [wsgi:info] [pid 5654:tid 139734168176384] [remote 192.168.60.1:50482] mod_wsgi (pid=5654, process='takemeds.com', application=''): Loading WSGI script '/etc/prod_wsgi.py'.
[Sun Mar 24 11:16:15.320432 2019] [wsgi:info] [pid 5654:tid 139734294390656] mod_wsgi (pid=5654): Shutdown requested 'takemeds.com'.
[Sun Mar 24 11:16:15.321211 2019] [wsgi:info] [pid 5654:tid 139734294390656] mod_wsgi (pid=5654): Stopping process 'takemeds.com'.
[Sun Mar 24 11:16:15.321425 2019] [wsgi:info] [pid 5654:tid 139734294390656] mod_wsgi (pid=5654): Destroying interpreters.
[Sun Mar 24 11:16:15.321437 2019] [wsgi:info] [pid 5654:tid 139734294390656] mod_wsgi (pid=5654): Cleanup interpreter ''.
[Sun Mar 24 11:16:15.321640 2019] [wsgi:info] [pid 5654:tid 139734294390656] mod_wsgi (pid=5654): Terminating Python.
[Sun Mar 24 11:16:15.455015 2019] [wsgi:info] [pid 5654:tid 139734294390656] mod_wsgi (pid=5654): Python has shutdown.
[Sun Mar 24 11:16:15.455059 2019] [wsgi:info] [pid 5654:tid 139734294390656] mod_wsgi (pid=5654): Exiting process 'takemeds.com'.
[Sun Mar 24 16:46:16.623191 2019] [wsgi:info] [pid 5853:tid 140507000461184] mod_wsgi (pid=5853): Attach interpreter ''.
[Sun Mar 24 16:46:16.651230 2019] [wsgi:info] [pid 5853:tid 140507000461184] mod_wsgi (pid=5853): Adding '/home/zahlen/takemeds' to path.
[Sun Mar 24 16:49:48.265614 2019] [wsgi:info] [pid 5853:tid 140506849068800] [remote 192.168.60.1:50834] mod_wsgi (pid=5853, process='takemeds.com', application=''): Loading WSGI script '/etc/prod_wsgi.py'.
[Sun Mar 24 11:21:39.185937 2019] [wsgi:info] [pid 5853:tid 140507000461184] mod_wsgi (pid=5853): Shutdown requested 'takemeds.com'.
[Sun Mar 24 11:21:39.187012 2019] [wsgi:info] [pid 5853:tid 140507000461184] mod_wsgi (pid=5853): Stopping process 'takemeds.com'.
[Sun Mar 24 11:21:39.187038 2019] [wsgi:info] [pid 5853:tid 140507000461184] mod_wsgi (pid=5853): Destroying interpreters.
[Sun Mar 24 11:21:39.187052 2019] [wsgi:info] [pid 5853:tid 140507000461184] mod_wsgi (pid=5853): Cleanup interpreter ''.
[Sun Mar 24 11:21:39.187521 2019] [wsgi:info] [pid 5853:tid 140507000461184] mod_wsgi (pid=5853): Terminating Python.
[Sun Mar 24 11:21:39.317480 2019] [wsgi:info] [pid 5853:tid 140507000461184] mod_wsgi (pid=5853): Python has shutdown.
[Sun Mar 24 11:21:39.317522 2019] [wsgi:info] [pid 5853:tid 140507000461184] mod_wsgi (pid=5853): Exiting process 'takemeds.com'.
